linters:
  enable:
    - revive
linters-settings:
  revive:
    rules:
      #      - name: add-constant
      - name: argument-limit
      - name: blank-imports
      - name: bool-literal-in-expr
      #      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      #      - name: cyclomatic
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      #      - name: flag-parameter
#      - name: function-length
      #      - name: function-result-limit
      #      - name: get-return
      - name: if-return
      - name: identical-branches
      - name: increment-decrement
      - name: indent-error-flow
      - name: line-length-limit
        arguments:
          - 120
      - name: nested-structs
      - name: package-comments
      - name: range
      - name: range-val-address
      - name: range-val-in-closure
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: var-declaration
      - name: var-naming
issues:
  exclude-rules:
    # For some reason this picks up a lot of false positives for methods on generic types:
    - path: 'internal/protocol/dht/ktable/(.+)\.go'
      linters:
        - unused
