issues:
  exclude-rules:
    # For some reason this picks up a lot of false positives for methods on generic types:
    - path: 'internal/protocol/dht/ktable/(.+)\.go'
      linters:
        - unused
    # False positive: `Error: cannot infer T (internal/boilerplate/config/configfx/factory.go:9:22) (typecheck)`
    - path: 'internal/boilerplate/config/configfx/factory.go'
      linters:
        - typecheck
