FROM debian:bookworm-slim

# Set environment variables to make non-interactive installs
ENV DEBIAN_FRONTEND=noninteractive

# Create a new user and group
ARG USERNAME=bitmagnet
ARG UID=1000
ARG GID=1000

# Set the working directory
WORKDIR /home/${USERNAME}
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    git \
    sudo \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -g ${GID} ${USERNAME} && \
    useradd -m -u ${UID} -g ${GID} -s /bin/bash ${USERNAME} && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

RUN touch /home/${USERNAME}/.bashrc && chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.bashrc

RUN mkdir /nix && chown ${USERNAME}:${USERNAME} /nix

RUN mkdir -p /etc/nix && chown ${USERNAME}:${USERNAME} /etc/nix

RUN mkdir -p /home/${USERNAME}/.local/bin

RUN mkdir -p /home/${USERNAME}/code

RUN chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}

COPY ./entrypoint-dev.sh /bin/entrypoint.sh

RUN chmod +x /bin/entrypoint.sh

USER ${USERNAME}

RUN echo "warn-dirty = false" >> /etc/nix/nix.conf
RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
RUN echo "filter-syscalls = false" >> /etc/nix/nix.conf
RUN echo "build-users-group = ubuntu" >> /etc/nix/nix.conf

ENV HOME=/home/${USERNAME} \
    PATH=/home/${USERNAME}/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/${USERNAME}/.local/bin:/nix/var/nix/profiles/default/sbin:/bin:/sbin:/usr/bin:/usr/sbin \
    NIX_PATH=/nix/var/nix/profiles/per-user/${USERNAME}/channels

RUN curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh -s -- --no-daemon --yes

RUN echo ". /home/${USERNAME}/.nix-profile/etc/profile.d/nix.sh" >> /home/bitmagnet/.bashrc

RUN mkdir -p /home/${USERNAME}/go/pkg/mod/cache && \
    chown ${USERNAME}:${USERNAME} /home/${USERNAME}/go/pkg/mod/cache && \
    mkdir -p /home/${USERNAME}/.cache && \
    chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.cache

ENTRYPOINT ["tail", "-f", "/dev/null"]
