// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: common/model/model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type Torrent_FilesStatus int32

const (
	Torrent_no_info        Torrent_FilesStatus = 0
	Torrent_single         Torrent_FilesStatus = 1
	Torrent_multi          Torrent_FilesStatus = 2
	Torrent_over_threshold Torrent_FilesStatus = 3
)

var (
	Torrent_FilesStatus_name = map[int32]string{
		int32(0): "no_info",
		int32(1): "single",
		int32(2): "multi",
		int32(3): "over_threshold",
	}

	Torrent_FilesStatus_value = map[string]int32{
		"no_info":        int32(0),
		"single":         int32(1),
		"multi":          int32(2),
		"over_threshold": int32(3),
	}
)

func (x Torrent_FilesStatus) Enum() *Torrent_FilesStatus {
	p := new(Torrent_FilesStatus)
	*p = x
	return p
}

type Torrent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	InfoHash      string              `json:"infoHash,omitempty" protobuf:"bytes,1,opt,name=infoHash,proto3"`
	Name          string              `json:"name,omitempty" protobuf:"bytes,2,opt,name=name,proto3"`
	Size          int64               `json:"size,omitempty" protobuf:"varint,4,opt,name=size,proto3"`
	Private       bool                `json:"private,omitempty" protobuf:"varint,5,opt,name=private,proto3"`
	FilesStatus   Torrent_FilesStatus `json:"filesStatus,omitempty" protobuf:"varint,6,opt,name=filesStatus,proto3,enum=model.Torrent_FilesStatus"`
	Extension     *string             `json:"extension,omitempty" protobuf:"bytes,7,opt,name=extension,proto3,oneof"`
	Files         []*TorrentFile      `json:"files,omitempty" protobuf:"bytes,8,rep,name=files,proto3"`
	FilesCount    *int32              `json:"filesCount,omitempty" protobuf:"varint,9,opt,name=filesCount,proto3,oneof"`
	Tags          []string            `json:"tags,omitempty" protobuf:"bytes,10,rep,name=tags,proto3"`
	Sources       []*TorrentSource    `json:"sources,omitempty" protobuf:"bytes,11,rep,name=sources,proto3"`
	CreatedAt     int64               `json:"createdAt,omitempty" protobuf:"varint,12,opt,name=createdAt,proto3"`
	UpdatedAt     int64               `json:"updatedAt,omitempty" protobuf:"varint,13,opt,name=updatedAt,proto3"`
}

func (x *Torrent) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Torrent) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}

	var zero string

	return zero
}

func (x *Torrent) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

func (x *Torrent) GetSize() int64 {
	if x != nil {
		return x.Size
	}

	var zero int64

	return zero
}

func (x *Torrent) GetPrivate() bool {
	if x != nil {
		return x.Private
	}

	var zero bool

	return zero
}

func (x *Torrent) GetFilesStatus() Torrent_FilesStatus {
	if x != nil {
		return x.FilesStatus
	}

	var zero Torrent_FilesStatus

	return zero
}

func (x *Torrent) GetExtension() *string {
	if x != nil {
		return x.Extension
	}

	var zero *string

	return zero
}

func (x *Torrent) GetFiles() []*TorrentFile {
	if x != nil {
		return x.Files
	}

	var zero []*TorrentFile

	return zero
}

func (x *Torrent) GetFilesCount() *int32 {
	if x != nil {
		return x.FilesCount
	}

	var zero *int32

	return zero
}

func (x *Torrent) GetTags() []string {
	if x != nil {
		return x.Tags
	}

	var zero []string

	return zero
}

func (x *Torrent) GetSources() []*TorrentSource {
	if x != nil {
		return x.Sources
	}

	var zero []*TorrentSource

	return zero
}

func (x *Torrent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}

	var zero int64

	return zero
}

func (x *Torrent) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}

	var zero int64

	return zero
}

type TorrentFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	InfoHash      string  `json:"infoHash,omitempty" protobuf:"bytes,1,opt,name=infoHash,proto3"`
	Index         int32   `json:"index,omitempty" protobuf:"varint,2,opt,name=index,proto3"`
	Path          string  `json:"path,omitempty" protobuf:"bytes,3,opt,name=path,proto3"`
	Extension     *string `json:"extension,omitempty" protobuf:"bytes,4,opt,name=extension,proto3,oneof"`
	FileType      *string `json:"fileType,omitempty" protobuf:"bytes,5,opt,name=fileType,proto3,oneof"`
	Size          int64   `json:"size,omitempty" protobuf:"varint,6,opt,name=size,proto3"`
	CreatedAt     int64   `json:"createdAt,omitempty" protobuf:"varint,7,opt,name=createdAt,proto3"`
	UpdatedAt     int64   `json:"updatedAt,omitempty" protobuf:"varint,8,opt,name=updatedAt,proto3"`
}

func (x *TorrentFile) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *TorrentFile) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}

	var zero string

	return zero
}

func (x *TorrentFile) GetIndex() int32 {
	if x != nil {
		return x.Index
	}

	var zero int32

	return zero
}

func (x *TorrentFile) GetPath() string {
	if x != nil {
		return x.Path
	}

	var zero string

	return zero
}

func (x *TorrentFile) GetExtension() *string {
	if x != nil {
		return x.Extension
	}

	var zero *string

	return zero
}

func (x *TorrentFile) GetFileType() *string {
	if x != nil {
		return x.FileType
	}

	var zero *string

	return zero
}

func (x *TorrentFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}

	var zero int64

	return zero
}

func (x *TorrentFile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}

	var zero int64

	return zero
}

func (x *TorrentFile) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}

	var zero int64

	return zero
}

type TorrentSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	InfoHash      string  `json:"infoHash,omitempty" protobuf:"bytes,1,opt,name=infoHash,proto3"`
	Source        string  `json:"source,omitempty" protobuf:"bytes,2,opt,name=source,proto3"`
	ImportId      *string `json:"importId,omitempty" protobuf:"bytes,3,opt,name=importId,proto3,oneof"`
	Seeders       *int32  `json:"seeders,omitempty" protobuf:"varint,4,opt,name=seeders,proto3,oneof"`
	Leechers      *int32  `json:"leechers,omitempty" protobuf:"varint,5,opt,name=leechers,proto3,oneof"`
	PublishedAt   *int64  `json:"publishedAt,omitempty" protobuf:"varint,6,opt,name=publishedAt,proto3,oneof"`
	CreatedAt     int64   `json:"createdAt,omitempty" protobuf:"varint,7,opt,name=createdAt,proto3"`
	UpdatedAt     int64   `json:"updatedAt,omitempty" protobuf:"varint,8,opt,name=updatedAt,proto3"`
}

func (x *TorrentSource) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *TorrentSource) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}

	var zero string

	return zero
}

func (x *TorrentSource) GetSource() string {
	if x != nil {
		return x.Source
	}

	var zero string

	return zero
}

func (x *TorrentSource) GetImportId() *string {
	if x != nil {
		return x.ImportId
	}

	var zero *string

	return zero
}

func (x *TorrentSource) GetSeeders() *int32 {
	if x != nil {
		return x.Seeders
	}

	var zero *int32

	return zero
}

func (x *TorrentSource) GetLeechers() *int32 {
	if x != nil {
		return x.Leechers
	}

	var zero *int32

	return zero
}

func (x *TorrentSource) GetPublishedAt() *int64 {
	if x != nil {
		return x.PublishedAt
	}

	var zero *int64

	return zero
}

func (x *TorrentSource) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}

	var zero int64

	return zero
}

func (x *TorrentSource) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}

	var zero int64

	return zero
}

type TorrentContent struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	Id              string      `json:"id,omitempty" protobuf:"bytes,1,opt,name=id,proto3"`
	InfoHash        string      `json:"infoHash,omitempty" protobuf:"bytes,2,opt,name=infoHash,proto3"`
	ContentType     *string     `json:"contentType,omitempty" protobuf:"bytes,3,opt,name=contentType,proto3,oneof"`
	ContentRef      *ContentRef `json:"contentRef,omitempty" protobuf:"bytes,4,opt,name=contentRef,proto3,oneof"`
	Languages       []string    `json:"languages,omitempty" protobuf:"bytes,5,rep,name=languages,proto3"`
	Episodes        []string    `json:"episodes,omitempty" protobuf:"bytes,6,rep,name=episodes,proto3"`
	VideoResolution *string     `json:"videoResolution,omitempty" protobuf:"bytes,7,opt,name=videoResolution,proto3,oneof"`
	VideoSource     *string     `json:"videoSource,omitempty" protobuf:"bytes,8,opt,name=videoSource,proto3,oneof"`
	VideoCodec      *string     `json:"videoCodec,omitempty" protobuf:"bytes,9,opt,name=videoCodec,proto3,oneof"`
	Video3D         *string     `json:"video3d,omitempty" protobuf:"bytes,10,opt,name=video3d,proto3,oneof"`
	VideoModifier   *string     `json:"videoModifier,omitempty" protobuf:"bytes,11,opt,name=videoModifier,proto3,oneof"`
	ReleaseGroup    *string     `json:"releaseGroup,omitempty" protobuf:"bytes,12,opt,name=releaseGroup,proto3,oneof"`
	Seeders         *int32      `json:"seeders,omitempty" protobuf:"varint,13,opt,name=seeders,proto3,oneof"`
	Leechers        *int32      `json:"leechers,omitempty" protobuf:"varint,14,opt,name=leechers,proto3,oneof"`
	Size            int64       `json:"size,omitempty" protobuf:"varint,15,opt,name=size,proto3"`
	FilesCount      *int32      `json:"filesCount,omitempty" protobuf:"varint,16,opt,name=filesCount,proto3,oneof"`
	Tags            []string    `json:"tags,omitempty" protobuf:"bytes,17,rep,name=tags,proto3"`
	PublishedAt     int64       `json:"publishedAt,omitempty" protobuf:"varint,18,opt,name=publishedAt,proto3"`
	CreatedAt       int64       `json:"createdAt,omitempty" protobuf:"varint,19,opt,name=createdAt,proto3"`
	UpdatedAt       int64       `json:"updatedAt,omitempty" protobuf:"varint,20,opt,name=updatedAt,proto3"`
	Torrent         *Torrent    `json:"torrent,omitempty" protobuf:"bytes,21,opt,name=torrent,proto3"`
	Content         *Content    `json:"content,omitempty" protobuf:"bytes,22,opt,name=content,proto3"`
}

func (x *TorrentContent) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *TorrentContent) GetId() string {
	if x != nil {
		return x.Id
	}

	var zero string

	return zero
}

func (x *TorrentContent) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}

	var zero string

	return zero
}

func (x *TorrentContent) GetContentType() *string {
	if x != nil {
		return x.ContentType
	}

	var zero *string

	return zero
}

func (x *TorrentContent) GetContentRef() *ContentRef {
	if x != nil {
		return x.ContentRef
	}

	var zero *ContentRef

	return zero
}

func (x *TorrentContent) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}

	var zero []string

	return zero
}

func (x *TorrentContent) GetEpisodes() []string {
	if x != nil {
		return x.Episodes
	}

	var zero []string

	return zero
}

func (x *TorrentContent) GetVideoResolution() *string {
	if x != nil {
		return x.VideoResolution
	}

	var zero *string

	return zero
}

func (x *TorrentContent) GetVideoSource() *string {
	if x != nil {
		return x.VideoSource
	}

	var zero *string

	return zero
}

func (x *TorrentContent) GetVideoCodec() *string {
	if x != nil {
		return x.VideoCodec
	}

	var zero *string

	return zero
}

func (x *TorrentContent) GetVideo3D() *string {
	if x != nil {
		return x.Video3D
	}

	var zero *string

	return zero
}

func (x *TorrentContent) GetVideoModifier() *string {
	if x != nil {
		return x.VideoModifier
	}

	var zero *string

	return zero
}

func (x *TorrentContent) GetReleaseGroup() *string {
	if x != nil {
		return x.ReleaseGroup
	}

	var zero *string

	return zero
}

func (x *TorrentContent) GetSeeders() *int32 {
	if x != nil {
		return x.Seeders
	}

	var zero *int32

	return zero
}

func (x *TorrentContent) GetLeechers() *int32 {
	if x != nil {
		return x.Leechers
	}

	var zero *int32

	return zero
}

func (x *TorrentContent) GetSize() int64 {
	if x != nil {
		return x.Size
	}

	var zero int64

	return zero
}

func (x *TorrentContent) GetFilesCount() *int32 {
	if x != nil {
		return x.FilesCount
	}

	var zero *int32

	return zero
}

func (x *TorrentContent) GetTags() []string {
	if x != nil {
		return x.Tags
	}

	var zero []string

	return zero
}

func (x *TorrentContent) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}

	var zero int64

	return zero
}

func (x *TorrentContent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}

	var zero int64

	return zero
}

func (x *TorrentContent) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}

	var zero int64

	return zero
}

func (x *TorrentContent) GetTorrent() *Torrent {
	if x != nil {
		return x.Torrent
	}

	var zero *Torrent

	return zero
}

func (x *TorrentContent) GetContent() *Content {
	if x != nil {
		return x.Content
	}

	var zero *Content

	return zero
}

type Content struct {
	state            protoimpl.MessageState
	sizeCache        protoimpl.SizeCache
	unknownFields    protoimpl.UnknownFields
	Ref              *ContentRef          `json:"ref,omitempty" protobuf:"bytes,1,opt,name=ref,proto3"`
	Title            string               `json:"title,omitempty" protobuf:"bytes,2,opt,name=title,proto3"`
	ReleaseDate      *Date                `json:"releaseDate,omitempty" protobuf:"bytes,3,opt,name=releaseDate,proto3,oneof"`
	Adult            *bool                `json:"adult,omitempty" protobuf:"varint,4,opt,name=adult,proto3,oneof"`
	OriginalLanguage *string              `json:"originalLanguage,omitempty" protobuf:"bytes,5,opt,name=originalLanguage,proto3,oneof"`
	OriginalTitle    *string              `json:"originalTitle,omitempty" protobuf:"bytes,6,opt,name=originalTitle,proto3,oneof"`
	Overview         *string              `json:"overview,omitempty" protobuf:"bytes,7,opt,name=overview,proto3,oneof"`
	Runtime          *int32               `json:"runtime,omitempty" protobuf:"varint,8,opt,name=runtime,proto3,oneof"`
	Popularity       *float32             `json:"popularity,omitempty" protobuf:"fixed32,9,opt,name=popularity,proto3,oneof"`
	VoteAverage      *float32             `json:"voteAverage,omitempty" protobuf:"fixed32,10,opt,name=voteAverage,proto3,oneof"`
	VoteCount        *int32               `json:"voteCount,omitempty" protobuf:"varint,11,opt,name=voteCount,proto3,oneof"`
	Tags             []string             `json:"tags,omitempty" protobuf:"bytes,12,rep,name=tags,proto3"`
	Collections      []*ContentCollection `json:"collections,omitempty" protobuf:"bytes,13,rep,name=collections,proto3"`
	Attributes       []*ContentAttribute  `json:"attributes,omitempty" protobuf:"bytes,14,rep,name=attributes,proto3"`
	CreatedAt        int64                `json:"createdAt,omitempty" protobuf:"varint,15,opt,name=createdAt,proto3"`
	UpdatedAt        int64                `json:"updatedAt,omitempty" protobuf:"varint,16,opt,name=updatedAt,proto3"`
}

func (x *Content) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Content) GetRef() *ContentRef {
	if x != nil {
		return x.Ref
	}

	var zero *ContentRef

	return zero
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}

	var zero string

	return zero
}

func (x *Content) GetReleaseDate() *Date {
	if x != nil {
		return x.ReleaseDate
	}

	var zero *Date

	return zero
}

func (x *Content) GetAdult() *bool {
	if x != nil {
		return x.Adult
	}

	var zero *bool

	return zero
}

func (x *Content) GetOriginalLanguage() *string {
	if x != nil {
		return x.OriginalLanguage
	}

	var zero *string

	return zero
}

func (x *Content) GetOriginalTitle() *string {
	if x != nil {
		return x.OriginalTitle
	}

	var zero *string

	return zero
}

func (x *Content) GetOverview() *string {
	if x != nil {
		return x.Overview
	}

	var zero *string

	return zero
}

func (x *Content) GetRuntime() *int32 {
	if x != nil {
		return x.Runtime
	}

	var zero *int32

	return zero
}

func (x *Content) GetPopularity() *float32 {
	if x != nil {
		return x.Popularity
	}

	var zero *float32

	return zero
}

func (x *Content) GetVoteAverage() *float32 {
	if x != nil {
		return x.VoteAverage
	}

	var zero *float32

	return zero
}

func (x *Content) GetVoteCount() *int32 {
	if x != nil {
		return x.VoteCount
	}

	var zero *int32

	return zero
}

func (x *Content) GetTags() []string {
	if x != nil {
		return x.Tags
	}

	var zero []string

	return zero
}

func (x *Content) GetCollections() []*ContentCollection {
	if x != nil {
		return x.Collections
	}

	var zero []*ContentCollection

	return zero
}

func (x *Content) GetAttributes() []*ContentAttribute {
	if x != nil {
		return x.Attributes
	}

	var zero []*ContentAttribute

	return zero
}

func (x *Content) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}

	var zero int64

	return zero
}

func (x *Content) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}

	var zero int64

	return zero
}

type ContentRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Type          string `json:"type,omitempty" protobuf:"bytes,1,opt,name=type,proto3"`
	Source        string `json:"source,omitempty" protobuf:"bytes,2,opt,name=source,proto3"`
	Id            string `json:"id,omitempty" protobuf:"bytes,3,opt,name=id,proto3"`
}

func (x *ContentRef) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *ContentRef) GetType() string {
	if x != nil {
		return x.Type
	}

	var zero string

	return zero
}

func (x *ContentRef) GetSource() string {
	if x != nil {
		return x.Source
	}

	var zero string

	return zero
}

func (x *ContentRef) GetId() string {
	if x != nil {
		return x.Id
	}

	var zero string

	return zero
}

type ContentCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Type          string `json:"type,omitempty" protobuf:"bytes,1,opt,name=type,proto3"`
	Source        string `json:"source,omitempty" protobuf:"bytes,2,opt,name=source,proto3"`
	Id            string `json:"id,omitempty" protobuf:"bytes,3,opt,name=id,proto3"`
	Name          string `json:"name,omitempty" protobuf:"bytes,4,opt,name=name,proto3"`
	CreatedAt     int64  `json:"createdAt,omitempty" protobuf:"varint,5,opt,name=createdAt,proto3"`
	UpdatedAt     int64  `json:"updatedAt,omitempty" protobuf:"varint,6,opt,name=updatedAt,proto3"`
}

func (x *ContentCollection) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *ContentCollection) GetType() string {
	if x != nil {
		return x.Type
	}

	var zero string

	return zero
}

func (x *ContentCollection) GetSource() string {
	if x != nil {
		return x.Source
	}

	var zero string

	return zero
}

func (x *ContentCollection) GetId() string {
	if x != nil {
		return x.Id
	}

	var zero string

	return zero
}

func (x *ContentCollection) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

func (x *ContentCollection) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}

	var zero int64

	return zero
}

func (x *ContentCollection) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}

	var zero int64

	return zero
}

type ContentAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Source        string `json:"source,omitempty" protobuf:"bytes,1,opt,name=source,proto3"`
	Key           string `json:"key,omitempty" protobuf:"bytes,2,opt,name=key,proto3"`
	Value         string `json:"value,omitempty" protobuf:"bytes,3,opt,name=value,proto3"`
	CreatedAt     int64  `json:"createdAt,omitempty" protobuf:"varint,4,opt,name=createdAt,proto3"`
	UpdatedAt     int64  `json:"updatedAt,omitempty" protobuf:"varint,5,opt,name=updatedAt,proto3"`
}

func (x *ContentAttribute) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *ContentAttribute) GetSource() string {
	if x != nil {
		return x.Source
	}

	var zero string

	return zero
}

func (x *ContentAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}

	var zero string

	return zero
}

func (x *ContentAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}

	var zero string

	return zero
}

func (x *ContentAttribute) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}

	var zero int64

	return zero
}

func (x *ContentAttribute) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}

	var zero int64

	return zero
}

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Year          int32  `json:"year,omitempty" protobuf:"varint,1,opt,name=year,proto3"`
	Month         *int32 `json:"month,omitempty" protobuf:"varint,2,opt,name=month,proto3,oneof"`
	Day           *int32 `json:"day,omitempty" protobuf:"varint,3,opt,name=day,proto3,oneof"`
}

func (x *Date) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}

	var zero int32

	return zero
}

func (x *Date) GetMonth() *int32 {
	if x != nil {
		return x.Month
	}

	var zero *int32

	return zero
}

func (x *Date) GetDay() *int32 {
	if x != nil {
		return x.Day
	}

	var zero *int32

	return zero
}
