// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bitmagnet-io/bitmagnet/internal/model"
)

func newAPIKeyPermission(db *gorm.DB, opts ...gen.DOOption) aPIKeyPermission {
	_aPIKeyPermission := aPIKeyPermission{}

	_aPIKeyPermission.aPIKeyPermissionDo.UseDB(db, opts...)
	_aPIKeyPermission.aPIKeyPermissionDo.UseModel(&model.APIKeyPermission{})

	tableName := _aPIKeyPermission.aPIKeyPermissionDo.TableName()
	_aPIKeyPermission.ALL = field.NewAsterisk(tableName)
	_aPIKeyPermission.APIKeyID = field.NewInt(tableName, "api_key_id")
	_aPIKeyPermission.Namespace = field.NewString(tableName, "namespace")
	_aPIKeyPermission.Object = field.NewString(tableName, "object")
	_aPIKeyPermission.Action = field.NewString(tableName, "action")

	_aPIKeyPermission.fillFieldMap()

	return _aPIKeyPermission
}

type aPIKeyPermission struct {
	aPIKeyPermissionDo

	ALL       field.Asterisk
	APIKeyID  field.Int
	Namespace field.String
	Object    field.String
	Action    field.String

	fieldMap map[string]field.Expr
}

func (a aPIKeyPermission) Table(newTableName string) *aPIKeyPermission {
	a.aPIKeyPermissionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aPIKeyPermission) As(alias string) *aPIKeyPermission {
	a.aPIKeyPermissionDo.DO = *(a.aPIKeyPermissionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aPIKeyPermission) updateTableName(table string) *aPIKeyPermission {
	a.ALL = field.NewAsterisk(table)
	a.APIKeyID = field.NewInt(table, "api_key_id")
	a.Namespace = field.NewString(table, "namespace")
	a.Object = field.NewString(table, "object")
	a.Action = field.NewString(table, "action")

	a.fillFieldMap()

	return a
}

func (a *aPIKeyPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aPIKeyPermission) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["api_key_id"] = a.APIKeyID
	a.fieldMap["namespace"] = a.Namespace
	a.fieldMap["object"] = a.Object
	a.fieldMap["action"] = a.Action
}

func (a aPIKeyPermission) clone(db *gorm.DB) aPIKeyPermission {
	a.aPIKeyPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aPIKeyPermission) replaceDB(db *gorm.DB) aPIKeyPermission {
	a.aPIKeyPermissionDo.ReplaceDB(db)
	return a
}

type aPIKeyPermissionDo struct{ gen.DO }

type IAPIKeyPermissionDo interface {
	gen.SubQuery
	Debug() IAPIKeyPermissionDo
	WithContext(ctx context.Context) IAPIKeyPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAPIKeyPermissionDo
	WriteDB() IAPIKeyPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAPIKeyPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAPIKeyPermissionDo
	Not(conds ...gen.Condition) IAPIKeyPermissionDo
	Or(conds ...gen.Condition) IAPIKeyPermissionDo
	Select(conds ...field.Expr) IAPIKeyPermissionDo
	Where(conds ...gen.Condition) IAPIKeyPermissionDo
	Order(conds ...field.Expr) IAPIKeyPermissionDo
	Distinct(cols ...field.Expr) IAPIKeyPermissionDo
	Omit(cols ...field.Expr) IAPIKeyPermissionDo
	Join(table schema.Tabler, on ...field.Expr) IAPIKeyPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAPIKeyPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAPIKeyPermissionDo
	Group(cols ...field.Expr) IAPIKeyPermissionDo
	Having(conds ...gen.Condition) IAPIKeyPermissionDo
	Limit(limit int) IAPIKeyPermissionDo
	Offset(offset int) IAPIKeyPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIKeyPermissionDo
	Unscoped() IAPIKeyPermissionDo
	Create(values ...*model.APIKeyPermission) error
	CreateInBatches(values []*model.APIKeyPermission, batchSize int) error
	Save(values ...*model.APIKeyPermission) error
	First() (*model.APIKeyPermission, error)
	Take() (*model.APIKeyPermission, error)
	Last() (*model.APIKeyPermission, error)
	Find() ([]*model.APIKeyPermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIKeyPermission, err error)
	FindInBatches(result *[]*model.APIKeyPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.APIKeyPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAPIKeyPermissionDo
	Assign(attrs ...field.AssignExpr) IAPIKeyPermissionDo
	Joins(fields ...field.RelationField) IAPIKeyPermissionDo
	Preload(fields ...field.RelationField) IAPIKeyPermissionDo
	FirstOrInit() (*model.APIKeyPermission, error)
	FirstOrCreate() (*model.APIKeyPermission, error)
	FindByPage(offset int, limit int) (result []*model.APIKeyPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAPIKeyPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aPIKeyPermissionDo) Debug() IAPIKeyPermissionDo {
	return a.withDO(a.DO.Debug())
}

func (a aPIKeyPermissionDo) WithContext(ctx context.Context) IAPIKeyPermissionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aPIKeyPermissionDo) ReadDB() IAPIKeyPermissionDo {
	return a.Clauses(dbresolver.Read)
}

func (a aPIKeyPermissionDo) WriteDB() IAPIKeyPermissionDo {
	return a.Clauses(dbresolver.Write)
}

func (a aPIKeyPermissionDo) Session(config *gorm.Session) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Session(config))
}

func (a aPIKeyPermissionDo) Clauses(conds ...clause.Expression) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aPIKeyPermissionDo) Returning(value interface{}, columns ...string) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aPIKeyPermissionDo) Not(conds ...gen.Condition) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aPIKeyPermissionDo) Or(conds ...gen.Condition) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aPIKeyPermissionDo) Select(conds ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aPIKeyPermissionDo) Where(conds ...gen.Condition) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aPIKeyPermissionDo) Order(conds ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aPIKeyPermissionDo) Distinct(cols ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aPIKeyPermissionDo) Omit(cols ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aPIKeyPermissionDo) Join(table schema.Tabler, on ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aPIKeyPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aPIKeyPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aPIKeyPermissionDo) Group(cols ...field.Expr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aPIKeyPermissionDo) Having(conds ...gen.Condition) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aPIKeyPermissionDo) Limit(limit int) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aPIKeyPermissionDo) Offset(offset int) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aPIKeyPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aPIKeyPermissionDo) Unscoped() IAPIKeyPermissionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aPIKeyPermissionDo) Create(values ...*model.APIKeyPermission) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aPIKeyPermissionDo) CreateInBatches(values []*model.APIKeyPermission, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aPIKeyPermissionDo) Save(values ...*model.APIKeyPermission) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aPIKeyPermissionDo) First() (*model.APIKeyPermission, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIKeyPermission), nil
	}
}

func (a aPIKeyPermissionDo) Take() (*model.APIKeyPermission, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIKeyPermission), nil
	}
}

func (a aPIKeyPermissionDo) Last() (*model.APIKeyPermission, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIKeyPermission), nil
	}
}

func (a aPIKeyPermissionDo) Find() ([]*model.APIKeyPermission, error) {
	result, err := a.DO.Find()
	return result.([]*model.APIKeyPermission), err
}

func (a aPIKeyPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIKeyPermission, err error) {
	buf := make([]*model.APIKeyPermission, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aPIKeyPermissionDo) FindInBatches(result *[]*model.APIKeyPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aPIKeyPermissionDo) Attrs(attrs ...field.AssignExpr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aPIKeyPermissionDo) Assign(attrs ...field.AssignExpr) IAPIKeyPermissionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aPIKeyPermissionDo) Joins(fields ...field.RelationField) IAPIKeyPermissionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aPIKeyPermissionDo) Preload(fields ...field.RelationField) IAPIKeyPermissionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aPIKeyPermissionDo) FirstOrInit() (*model.APIKeyPermission, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIKeyPermission), nil
	}
}

func (a aPIKeyPermissionDo) FirstOrCreate() (*model.APIKeyPermission, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIKeyPermission), nil
	}
}

func (a aPIKeyPermissionDo) FindByPage(offset int, limit int) (result []*model.APIKeyPermission, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aPIKeyPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aPIKeyPermissionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aPIKeyPermissionDo) Delete(models ...*model.APIKeyPermission) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aPIKeyPermissionDo) withDO(do gen.Dao) *aPIKeyPermissionDo {
	a.DO = *do.(*gen.DO)
	return a
}
