// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bitmagnet-io/bitmagnet/internal/model"
)

func newContentTag(db *gorm.DB, opts ...gen.DOOption) contentTag {
	_contentTag := contentTag{}

	_contentTag.contentTagDo.UseDB(db, opts...)
	_contentTag.contentTagDo.UseModel(&model.ContentTag{})

	tableName := _contentTag.contentTagDo.TableName()
	_contentTag.ALL = field.NewAsterisk(tableName)
	_contentTag.ContentType = field.NewString(tableName, "content_type")
	_contentTag.ContentSource = field.NewString(tableName, "content_source")
	_contentTag.ContentID = field.NewString(tableName, "content_id")
	_contentTag.Name = field.NewString(tableName, "name")
	_contentTag.CreatedAt = field.NewTime(tableName, "created_at")
	_contentTag.UpdatedAt = field.NewTime(tableName, "updated_at")

	_contentTag.fillFieldMap()

	return _contentTag
}

type contentTag struct {
	contentTagDo

	ALL           field.Asterisk
	ContentType   field.String
	ContentSource field.String
	ContentID     field.String
	Name          field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (c contentTag) Table(newTableName string) *contentTag {
	c.contentTagDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contentTag) As(alias string) *contentTag {
	c.contentTagDo.DO = *(c.contentTagDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contentTag) updateTableName(table string) *contentTag {
	c.ALL = field.NewAsterisk(table)
	c.ContentType = field.NewString(table, "content_type")
	c.ContentSource = field.NewString(table, "content_source")
	c.ContentID = field.NewString(table, "content_id")
	c.Name = field.NewString(table, "name")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *contentTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contentTag) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["content_type"] = c.ContentType
	c.fieldMap["content_source"] = c.ContentSource
	c.fieldMap["content_id"] = c.ContentID
	c.fieldMap["name"] = c.Name
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c contentTag) clone(db *gorm.DB) contentTag {
	c.contentTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contentTag) replaceDB(db *gorm.DB) contentTag {
	c.contentTagDo.ReplaceDB(db)
	return c
}

type contentTagDo struct{ gen.DO }

type IContentTagDo interface {
	gen.SubQuery
	Debug() IContentTagDo
	WithContext(ctx context.Context) IContentTagDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IContentTagDo
	WriteDB() IContentTagDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IContentTagDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IContentTagDo
	Not(conds ...gen.Condition) IContentTagDo
	Or(conds ...gen.Condition) IContentTagDo
	Select(conds ...field.Expr) IContentTagDo
	Where(conds ...gen.Condition) IContentTagDo
	Order(conds ...field.Expr) IContentTagDo
	Distinct(cols ...field.Expr) IContentTagDo
	Omit(cols ...field.Expr) IContentTagDo
	Join(table schema.Tabler, on ...field.Expr) IContentTagDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IContentTagDo
	RightJoin(table schema.Tabler, on ...field.Expr) IContentTagDo
	Group(cols ...field.Expr) IContentTagDo
	Having(conds ...gen.Condition) IContentTagDo
	Limit(limit int) IContentTagDo
	Offset(offset int) IContentTagDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IContentTagDo
	Unscoped() IContentTagDo
	Create(values ...*model.ContentTag) error
	CreateInBatches(values []*model.ContentTag, batchSize int) error
	Save(values ...*model.ContentTag) error
	First() (*model.ContentTag, error)
	Take() (*model.ContentTag, error)
	Last() (*model.ContentTag, error)
	Find() ([]*model.ContentTag, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContentTag, err error)
	FindInBatches(result *[]*model.ContentTag, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ContentTag) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IContentTagDo
	Assign(attrs ...field.AssignExpr) IContentTagDo
	Joins(fields ...field.RelationField) IContentTagDo
	Preload(fields ...field.RelationField) IContentTagDo
	FirstOrInit() (*model.ContentTag, error)
	FirstOrCreate() (*model.ContentTag, error)
	FindByPage(offset int, limit int) (result []*model.ContentTag, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IContentTagDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c contentTagDo) Debug() IContentTagDo {
	return c.withDO(c.DO.Debug())
}

func (c contentTagDo) WithContext(ctx context.Context) IContentTagDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentTagDo) ReadDB() IContentTagDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentTagDo) WriteDB() IContentTagDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentTagDo) Session(config *gorm.Session) IContentTagDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentTagDo) Clauses(conds ...clause.Expression) IContentTagDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentTagDo) Returning(value interface{}, columns ...string) IContentTagDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentTagDo) Not(conds ...gen.Condition) IContentTagDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentTagDo) Or(conds ...gen.Condition) IContentTagDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentTagDo) Select(conds ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentTagDo) Where(conds ...gen.Condition) IContentTagDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentTagDo) Order(conds ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentTagDo) Distinct(cols ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentTagDo) Omit(cols ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentTagDo) Join(table schema.Tabler, on ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentTagDo) RightJoin(table schema.Tabler, on ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentTagDo) Group(cols ...field.Expr) IContentTagDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentTagDo) Having(conds ...gen.Condition) IContentTagDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentTagDo) Limit(limit int) IContentTagDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentTagDo) Offset(offset int) IContentTagDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IContentTagDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentTagDo) Unscoped() IContentTagDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentTagDo) Create(values ...*model.ContentTag) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentTagDo) CreateInBatches(values []*model.ContentTag, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentTagDo) Save(values ...*model.ContentTag) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentTagDo) First() (*model.ContentTag, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTag), nil
	}
}

func (c contentTagDo) Take() (*model.ContentTag, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTag), nil
	}
}

func (c contentTagDo) Last() (*model.ContentTag, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTag), nil
	}
}

func (c contentTagDo) Find() ([]*model.ContentTag, error) {
	result, err := c.DO.Find()
	return result.([]*model.ContentTag), err
}

func (c contentTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContentTag, err error) {
	buf := make([]*model.ContentTag, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentTagDo) FindInBatches(result *[]*model.ContentTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentTagDo) Attrs(attrs ...field.AssignExpr) IContentTagDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentTagDo) Assign(attrs ...field.AssignExpr) IContentTagDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentTagDo) Joins(fields ...field.RelationField) IContentTagDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentTagDo) Preload(fields ...field.RelationField) IContentTagDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentTagDo) FirstOrInit() (*model.ContentTag, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTag), nil
	}
}

func (c contentTagDo) FirstOrCreate() (*model.ContentTag, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTag), nil
	}
}

func (c contentTagDo) FindByPage(offset int, limit int) (result []*model.ContentTag, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentTagDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentTagDo) Delete(models ...*model.ContentTag) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentTagDo) withDO(do gen.Dao) *contentTagDo {
	c.DO = *do.(*gen.DO)
	return c
}
