// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bitmagnet-io/bitmagnet/internal/model"
)

func newInvitation(db *gorm.DB, opts ...gen.DOOption) invitation {
	_invitation := invitation{}

	_invitation.invitationDo.UseDB(db, opts...)
	_invitation.invitationDo.UseModel(&model.Invitation{})

	tableName := _invitation.invitationDo.TableName()
	_invitation.ALL = field.NewAsterisk(tableName)
	_invitation.Code = field.NewString(tableName, "code")
	_invitation.RoleName = field.NewString(tableName, "role_name")
	_invitation.Email = field.NewField(tableName, "email")
	_invitation.CreatedBy = field.NewField(tableName, "created_by")
	_invitation.ClaimedBy = field.NewField(tableName, "claimed_by")
	_invitation.ExpiresAt = field.NewField(tableName, "expires_at")
	_invitation.CreatedAt = field.NewTime(tableName, "created_at")
	_invitation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_invitation.CreatedByUser = invitationBelongsToCreatedByUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CreatedByUser", "model.User"),
		Role: struct {
			field.RelationField
			Permissions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("CreatedByUser.Role", "model.Role"),
			Permissions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreatedByUser.Role.Permissions", "model.RolePermission"),
			},
		},
		Permissions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("CreatedByUser.Permissions", "model.RolePermission"),
		},
	}

	_invitation.ClaimedByUser = invitationBelongsToClaimedByUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ClaimedByUser", "model.User"),
		Role: struct {
			field.RelationField
			Permissions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("ClaimedByUser.Role", "model.Role"),
			Permissions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ClaimedByUser.Role.Permissions", "model.RolePermission"),
			},
		},
		Permissions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ClaimedByUser.Permissions", "model.RolePermission"),
		},
	}

	_invitation.fillFieldMap()

	return _invitation
}

type invitation struct {
	invitationDo

	ALL           field.Asterisk
	Code          field.String
	RoleName      field.String
	Email         field.Field
	CreatedBy     field.Field
	ClaimedBy     field.Field
	ExpiresAt     field.Field
	CreatedAt     field.Time
	UpdatedAt     field.Time
	CreatedByUser invitationBelongsToCreatedByUser

	ClaimedByUser invitationBelongsToClaimedByUser

	fieldMap map[string]field.Expr
}

func (i invitation) Table(newTableName string) *invitation {
	i.invitationDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i invitation) As(alias string) *invitation {
	i.invitationDo.DO = *(i.invitationDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *invitation) updateTableName(table string) *invitation {
	i.ALL = field.NewAsterisk(table)
	i.Code = field.NewString(table, "code")
	i.RoleName = field.NewString(table, "role_name")
	i.Email = field.NewField(table, "email")
	i.CreatedBy = field.NewField(table, "created_by")
	i.ClaimedBy = field.NewField(table, "claimed_by")
	i.ExpiresAt = field.NewField(table, "expires_at")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *invitation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *invitation) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["code"] = i.Code
	i.fieldMap["role_name"] = i.RoleName
	i.fieldMap["email"] = i.Email
	i.fieldMap["created_by"] = i.CreatedBy
	i.fieldMap["claimed_by"] = i.ClaimedBy
	i.fieldMap["expires_at"] = i.ExpiresAt
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt

}

func (i invitation) clone(db *gorm.DB) invitation {
	i.invitationDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i invitation) replaceDB(db *gorm.DB) invitation {
	i.invitationDo.ReplaceDB(db)
	return i
}

type invitationBelongsToCreatedByUser struct {
	db *gorm.DB

	field.RelationField

	Role struct {
		field.RelationField
		Permissions struct {
			field.RelationField
		}
	}
	Permissions struct {
		field.RelationField
	}
}

func (a invitationBelongsToCreatedByUser) Where(conds ...field.Expr) *invitationBelongsToCreatedByUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a invitationBelongsToCreatedByUser) WithContext(ctx context.Context) *invitationBelongsToCreatedByUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a invitationBelongsToCreatedByUser) Session(session *gorm.Session) *invitationBelongsToCreatedByUser {
	a.db = a.db.Session(session)
	return &a
}

func (a invitationBelongsToCreatedByUser) Model(m *model.Invitation) *invitationBelongsToCreatedByUserTx {
	return &invitationBelongsToCreatedByUserTx{a.db.Model(m).Association(a.Name())}
}

type invitationBelongsToCreatedByUserTx struct{ tx *gorm.Association }

func (a invitationBelongsToCreatedByUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a invitationBelongsToCreatedByUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a invitationBelongsToCreatedByUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a invitationBelongsToCreatedByUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a invitationBelongsToCreatedByUserTx) Clear() error {
	return a.tx.Clear()
}

func (a invitationBelongsToCreatedByUserTx) Count() int64 {
	return a.tx.Count()
}

type invitationBelongsToClaimedByUser struct {
	db *gorm.DB

	field.RelationField

	Role struct {
		field.RelationField
		Permissions struct {
			field.RelationField
		}
	}
	Permissions struct {
		field.RelationField
	}
}

func (a invitationBelongsToClaimedByUser) Where(conds ...field.Expr) *invitationBelongsToClaimedByUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a invitationBelongsToClaimedByUser) WithContext(ctx context.Context) *invitationBelongsToClaimedByUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a invitationBelongsToClaimedByUser) Session(session *gorm.Session) *invitationBelongsToClaimedByUser {
	a.db = a.db.Session(session)
	return &a
}

func (a invitationBelongsToClaimedByUser) Model(m *model.Invitation) *invitationBelongsToClaimedByUserTx {
	return &invitationBelongsToClaimedByUserTx{a.db.Model(m).Association(a.Name())}
}

type invitationBelongsToClaimedByUserTx struct{ tx *gorm.Association }

func (a invitationBelongsToClaimedByUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a invitationBelongsToClaimedByUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a invitationBelongsToClaimedByUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a invitationBelongsToClaimedByUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a invitationBelongsToClaimedByUserTx) Clear() error {
	return a.tx.Clear()
}

func (a invitationBelongsToClaimedByUserTx) Count() int64 {
	return a.tx.Count()
}

type invitationDo struct{ gen.DO }

type IInvitationDo interface {
	gen.SubQuery
	Debug() IInvitationDo
	WithContext(ctx context.Context) IInvitationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInvitationDo
	WriteDB() IInvitationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInvitationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInvitationDo
	Not(conds ...gen.Condition) IInvitationDo
	Or(conds ...gen.Condition) IInvitationDo
	Select(conds ...field.Expr) IInvitationDo
	Where(conds ...gen.Condition) IInvitationDo
	Order(conds ...field.Expr) IInvitationDo
	Distinct(cols ...field.Expr) IInvitationDo
	Omit(cols ...field.Expr) IInvitationDo
	Join(table schema.Tabler, on ...field.Expr) IInvitationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInvitationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInvitationDo
	Group(cols ...field.Expr) IInvitationDo
	Having(conds ...gen.Condition) IInvitationDo
	Limit(limit int) IInvitationDo
	Offset(offset int) IInvitationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInvitationDo
	Unscoped() IInvitationDo
	Create(values ...*model.Invitation) error
	CreateInBatches(values []*model.Invitation, batchSize int) error
	Save(values ...*model.Invitation) error
	First() (*model.Invitation, error)
	Take() (*model.Invitation, error)
	Last() (*model.Invitation, error)
	Find() ([]*model.Invitation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Invitation, err error)
	FindInBatches(result *[]*model.Invitation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Invitation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInvitationDo
	Assign(attrs ...field.AssignExpr) IInvitationDo
	Joins(fields ...field.RelationField) IInvitationDo
	Preload(fields ...field.RelationField) IInvitationDo
	FirstOrInit() (*model.Invitation, error)
	FirstOrCreate() (*model.Invitation, error)
	FindByPage(offset int, limit int) (result []*model.Invitation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInvitationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i invitationDo) Debug() IInvitationDo {
	return i.withDO(i.DO.Debug())
}

func (i invitationDo) WithContext(ctx context.Context) IInvitationDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i invitationDo) ReadDB() IInvitationDo {
	return i.Clauses(dbresolver.Read)
}

func (i invitationDo) WriteDB() IInvitationDo {
	return i.Clauses(dbresolver.Write)
}

func (i invitationDo) Session(config *gorm.Session) IInvitationDo {
	return i.withDO(i.DO.Session(config))
}

func (i invitationDo) Clauses(conds ...clause.Expression) IInvitationDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i invitationDo) Returning(value interface{}, columns ...string) IInvitationDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i invitationDo) Not(conds ...gen.Condition) IInvitationDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i invitationDo) Or(conds ...gen.Condition) IInvitationDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i invitationDo) Select(conds ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i invitationDo) Where(conds ...gen.Condition) IInvitationDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i invitationDo) Order(conds ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i invitationDo) Distinct(cols ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i invitationDo) Omit(cols ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i invitationDo) Join(table schema.Tabler, on ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i invitationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i invitationDo) RightJoin(table schema.Tabler, on ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i invitationDo) Group(cols ...field.Expr) IInvitationDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i invitationDo) Having(conds ...gen.Condition) IInvitationDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i invitationDo) Limit(limit int) IInvitationDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i invitationDo) Offset(offset int) IInvitationDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i invitationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInvitationDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i invitationDo) Unscoped() IInvitationDo {
	return i.withDO(i.DO.Unscoped())
}

func (i invitationDo) Create(values ...*model.Invitation) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i invitationDo) CreateInBatches(values []*model.Invitation, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i invitationDo) Save(values ...*model.Invitation) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i invitationDo) First() (*model.Invitation, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invitation), nil
	}
}

func (i invitationDo) Take() (*model.Invitation, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invitation), nil
	}
}

func (i invitationDo) Last() (*model.Invitation, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invitation), nil
	}
}

func (i invitationDo) Find() ([]*model.Invitation, error) {
	result, err := i.DO.Find()
	return result.([]*model.Invitation), err
}

func (i invitationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Invitation, err error) {
	buf := make([]*model.Invitation, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i invitationDo) FindInBatches(result *[]*model.Invitation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i invitationDo) Attrs(attrs ...field.AssignExpr) IInvitationDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i invitationDo) Assign(attrs ...field.AssignExpr) IInvitationDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i invitationDo) Joins(fields ...field.RelationField) IInvitationDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i invitationDo) Preload(fields ...field.RelationField) IInvitationDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i invitationDo) FirstOrInit() (*model.Invitation, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invitation), nil
	}
}

func (i invitationDo) FirstOrCreate() (*model.Invitation, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invitation), nil
	}
}

func (i invitationDo) FindByPage(offset int, limit int) (result []*model.Invitation, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i invitationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i invitationDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i invitationDo) Delete(models ...*model.Invitation) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *invitationDo) withDO(do gen.Dao) *invitationDo {
	i.DO = *do.(*gen.DO)
	return i
}
