// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: host/search/search.proto

package search

import (
	"context"
	search "github.com/bitmagnet-io/bitmagnet/proto/common/search"
)

type SearchService interface {
	SearchTorrentContent(ctx context.Context, params *search.Params) (*search.TorrentContentResult, error)
}
