//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: host/search/search.proto

package search

import (
	"context"
	wasm "github.com/bitmagnet-io/bitmagnet/internal/wasm"
	search "github.com/bitmagnet-io/bitmagnet/proto/common/search"
	_ "unsafe"
)

type searchService struct{}

func NewSearchService() SearchService {
	return searchService{}
}

//go:wasmimport env search_torrent_content
func _search_torrent_content(ptr uint32, size uint32) uint64

func (h searchService) SearchTorrentContent(ctx context.Context, request *search.Params) (*search.TorrentContentResult, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _search_torrent_content(ptr, size)
	wasm.Free(ptr)
	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)
	response := new(search.TorrentContentResult)
	err = response.UnmarshalVT(buf)
	if err != nil {
		return nil, err
	}
	return response, nil
}
