package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/bitmagnet-io/bitmagnet/internal/config/json_schema"
	"github.com/bitmagnet-io/bitmagnet/internal/gql"
)

// Required is the resolver for the required field.
func (r *jSONSchemaResolver) Required(ctx context.Context, obj *json_schema.JSONSchema) (*json_schema.JSONValue, error) {
	if obj.Required == nil {
		return nil, nil
	}

	required, err := json_schema.NewValue(obj.Required)
	if err != nil {
		return nil, err
	}

	return &required, nil
}

// JSONSchema returns gql.JSONSchemaResolver implementation.
func (r *Resolver) JSONSchema() gql.JSONSchemaResolver { return &jSONSchemaResolver{r} }

type jSONSchemaResolver struct{ *Resolver }
