package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/bitmagnet-io/bitmagnet/internal/gql"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel"
)

// Torrent is the resolver for the torrent field.
func (r *mutationResolver) Torrent(ctx context.Context) (gqlmodel.TorrentMutation, error) {
	return gqlmodel.TorrentMutation{}, nil
}

// Queue is the resolver for the queue field.
func (r *mutationResolver) Queue(ctx context.Context) (gqlmodel.QueueMutation, error) {
	return gqlmodel.QueueMutation{QueueManager: r.QueueManager}, nil
}

// Worker is the resolver for the worker field.
func (r *mutationResolver) Worker(ctx context.Context) (gqlmodel.WorkerMutation, error) {
	return gqlmodel.WorkerMutation{
		Context:  r.Context,
		Registry: r.Workers,
	}, nil
}

// Config is the resolver for the config field.
func (r *mutationResolver) Config(ctx context.Context) (gqlmodel.ConfigMutation, error) {
	return gqlmodel.ConfigMutation{
		Manager: r.ConfigManager,
	}, nil
}

// Auth is the resolver for the auth field.
func (r *mutationResolver) Auth(ctx context.Context) (gqlmodel.AuthMutation, error) {
	return gqlmodel.AuthMutation{
		User: r.User,
		RBAC: r.RBAC,
	}, nil
}

// Self is the resolver for the self field.
func (r *mutationResolver) Self(ctx context.Context) (gqlmodel.SelfMutation, error) {
	return gqlmodel.SelfMutation{
		User:   r.User,
		RBAC:   r.RBAC,
		APIKey: r.APIKey,
	}, nil
}

// Target is the resolver for the target field.
func (r *mutationResolver) Target(ctx context.Context) (gqlmodel.TargetMutation, error) {
	return gqlmodel.TargetMutation{
		Targets: r.Targets,
	}, nil
}

// Mutation returns gql.MutationResolver implementation.
func (r *Resolver) Mutation() gql.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
