package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/bitmagnet-io/bitmagnet/internal/classifier"
	"github.com/bitmagnet-io/bitmagnet/internal/gql"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel/gen"
	"github.com/bitmagnet-io/bitmagnet/internal/model"
	"github.com/bitmagnet-io/bitmagnet/internal/persister"
	"github.com/bitmagnet-io/bitmagnet/internal/processor"
	"github.com/bitmagnet-io/bitmagnet/internal/protocol"
	adapter "github.com/bitmagnet-io/bitmagnet/internal/search"
	"github.com/bitmagnet-io/bitmagnet/internal/slice"
)

// Delete is the resolver for the delete field.
func (r *torrentMutationResolver) Delete(ctx context.Context, obj *gqlmodel.TorrentMutation, infoHashes []protocol.ID) (*string, error) {
	err := r.PersisterAdder.Add(
		ctx,
		persister.Inputs{
			persister.InputDeleteInfoHashes(infoHashes...),
			persister.InputFlush,
		}.Input(),
	)
	// err := r.Blocker.Block(ctx, infoHashes, true)
	return nil, err
}

// PutTags is the resolver for the putTags field.
func (r *torrentMutationResolver) PutTags(ctx context.Context, obj *gqlmodel.TorrentMutation, infoHashes []protocol.ID, tagNames []string) (*string, error) {
	dao, err := r.DaoProvider.Dao()
	if err != nil {
		return nil, err
	}

	return nil, dao.TorrentTag.Put(ctx, infoHashes, tagNames)
}

// SetTags is the resolver for the setTags field.
func (r *torrentMutationResolver) SetTags(ctx context.Context, obj *gqlmodel.TorrentMutation, infoHashes []protocol.ID, tagNames []string) (*string, error) {
	dao, err := r.DaoProvider.Dao()
	if err != nil {
		return nil, err
	}

	return nil, dao.TorrentTag.Set(ctx, infoHashes, tagNames)
}

// DeleteTags is the resolver for the deleteTags field.
func (r *torrentMutationResolver) DeleteTags(ctx context.Context, obj *gqlmodel.TorrentMutation, infoHashes []protocol.ID, tagNames []string) (*string, error) {
	dao, err := r.DaoProvider.Dao()
	if err != nil {
		return nil, err
	}

	return nil, dao.TorrentTag.Delete(ctx, infoHashes, tagNames)
}

// Reprocess is the resolver for the reprocess field.
func (r *torrentMutationResolver) Reprocess(ctx context.Context, obj *gqlmodel.TorrentMutation, input gen.TorrentReprocessInput) (*string, error) {
	params := processor.MessageParams{
		InfoHashes: input.InfoHashes,
		ClassifierParams: processor.ClassifierParams{
			ClassifierFlags: make(classifier.Flags),
		},
	}
	if w, ok := input.ClassifierWorkflow.ValueOK(); ok {
		params.ClassifierWorkflow = classifier.Workflow(*w)
	}

	if r, ok := input.ClassifierRematch.ValueOK(); ok && *r {
		params.ClassifyMode = processor.ClassifyModeRematch
	}

	if apisDisabled, ok := input.ApisDisabled.ValueOK(); ok {
		params.ClassifierFlags["apis_enabled"] = !*apisDisabled
	}

	if localSearchDisabled, ok := input.LocalSearchDisabled.ValueOK(); ok {
		params.ClassifierFlags["local_search_enabled"] = !*localSearchDisabled
	}

	return nil, r.Indexer.NewJob(params).Run(ctx)
}

// SearchTorrentContent is the resolver for the searchTorrentContent field.
func (r *torrentQueryResolver) SearchTorrentContent(ctx context.Context, obj *gqlmodel.TorrentQuery, input adapter.Params) (gqlmodel.BaseSearchResult[gqlmodel.TorrentContent], error) {
	result, err := r.Search.TorrentContent(ctx, input)

	return gqlmodel.TorrentContentSearchResult(gqlmodel.TorrentContentSearchResult{
		TotalCount:           result.TotalCount,
		TotalCountIsEstimate: result.TotalCountIsEstimate,
		HasNextPage:          result.HasNextPage,
		Facets:               result.Facets,
		Items: slice.Map(result.Items, func(item adapter.TorrentContentResultItem) gqlmodel.TorrentContent {
			var content *model.Content
			if item.Content.ID != "" {
				content = &item.Content
			}

			return gqlmodel.TorrentContent{
				TorrentContent: item.TorrentContent,
				Content:        content,
			}
		}),
	}), err
}

// Files is the resolver for the files field.
func (r *torrentQueryResolver) SearchTorrentFiles(ctx context.Context, obj *gqlmodel.TorrentQuery, input adapter.Params) (gqlmodel.BaseSearchResult[model.TorrentFile], error) {
	result, err := r.Search.TorrentFiles(ctx, input)

	return gqlmodel.TorrentFilesSearchResult(result), err
}

// TorrentMutation returns gql.TorrentMutationResolver implementation.
func (r *Resolver) TorrentMutation() gql.TorrentMutationResolver { return &torrentMutationResolver{r} }

// TorrentQuery returns gql.TorrentQueryResolver implementation.
func (r *Resolver) TorrentQuery() gql.TorrentQueryResolver { return &torrentQueryResolver{r} }

type torrentMutationResolver struct{ *Resolver }
type torrentQueryResolver struct{ *Resolver }
