// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameAPIKey = "api_keys"

// APIKey mapped from table <api_keys>
type APIKey struct {
	ID          int                `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int                `gorm:"column:user_id" json:"userId"`
	Hash        []byte             `gorm:"column:hash;not null" json:"-"`
	ExpiresAt   sql.NullTime       `gorm:"column:expires_at" json:"expiresAt"`
	CreatedAt   time.Time          `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
	User        User               `gorm:"foreignKey:ID;references:UserID" json:"user"`
	Permissions []APIKeyPermission `gorm:"foreignKey:APIKeyID;references:ID" json:"permissions"`
}

// TableName APIKey's table name
func (*APIKey) TableName() string {
	return TableNameAPIKey
}
