// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBloomFilter = "bloom_filters"

// BloomFilter mapped from table <bloom_filters>
type BloomFilter struct {
	Key       string    `gorm:"column:key;primaryKey" json:"key"`
	CreatedAt time.Time `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updatedAt"`
	Oid       string    `gorm:"column:oid" json:"oid"`
}

// TableName BloomFilter's table name
func (*BloomFilter) TableName() string {
	return TableNameBloomFilter
}
