// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContentCollectionContent = "content_collections_content"

// ContentCollectionContent mapped from table <content_collections_content>
type ContentCollectionContent struct {
	ContentType             ContentType       `gorm:"column:content_type;primaryKey" json:"contentType"`
	ContentSource           string            `gorm:"column:content_source;primaryKey" json:"contentSource"`
	ContentID               string            `gorm:"column:content_id;primaryKey" json:"contentId"`
	ContentCollectionType   string            `gorm:"column:content_collection_type;primaryKey" json:"contentCollectionType"`
	ContentCollectionSource string            `gorm:"column:content_collection_source;primaryKey" json:"contentCollectionSource"`
	ContentCollectionID     string            `gorm:"column:content_collection_id;primaryKey" json:"contentCollectionId"`
	Content                 Content           `json:"content"`
	Collection              ContentCollection `gorm:"foreignKey:ContentCollectionType,ContentCollectionSource,ContentCollectionID;references:Type,Source,id" json:"collection"`
}

// TableName ContentCollectionContent's table name
func (*ContentCollectionContent) TableName() string {
	return TableNameContentCollectionContent
}
