// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermission = "role_permissions"

// RolePermission mapped from table <role_permissions>
type RolePermission struct {
	RoleName  string    `gorm:"column:role_name;primaryKey" json:"roleName"`
	Namespace string    `gorm:"column:namespace;primaryKey;<-:create" json:"namespace"`
	Object    string    `gorm:"column:object;primaryKey;<-:create" json:"object"`
	Action    string    `gorm:"column:action;primaryKey;<-:create" json:"action"`
	CreatedAt time.Time `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
