// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	Name        string           `gorm:"column:name;primaryKey;<-:create" json:"name"`
	Core        bool             `gorm:"column:core;not null;<-:false" json:"core"`
	CreatedAt   time.Time        `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
	UpdatedAt   time.Time        `gorm:"column:updated_at;not null" json:"updatedAt"`
	Permissions []RolePermission `gorm:"foreignKey:RoleName;references:Name" json:"permissions"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
