// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/bitmagnet-io/bitmagnet/internal/protocol"
)

const TableNameTorrentTag = "torrent_tags"

// TorrentTag mapped from table <torrent_tags>
type TorrentTag struct {
	InfoHash  protocol.ID `gorm:"column:info_hash;primaryKey;<-:create" json:"infoHash"`
	Name      string      `gorm:"column:name;primaryKey;<-:create" json:"name"`
	CreatedAt time.Time   `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
	UpdatedAt time.Time   `gorm:"column:updated_at;not null" json:"updatedAt"`
}

// TableName TorrentTag's table name
func (*TorrentTag) TableName() string {
	return TableNameTorrentTag
}
