server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: bitmagnet
    pipeline_stages:
      - json:
          expressions:
            time: timestamp
      - timestamp:
          source: time
          format: "2006-01-02T15:04:05.999999999Z07:00"
    static_configs:
      - targets:
          - localhost
        labels:
          job: bitmagnet
          __path__: /var/log/bitmagnet/*.log
