title: bitmagnet
tagline: "Self-hosted BitTorrent indexer, DHT crawler, content classifier and torrent search engine"
description: "A self-hosted BitTorrent indexer, DHT crawler, content classifier and torrent search engine with web UI, GraphQL API and Servarr stack integration."
baseurl: ""
url: "https://bitmagnet.io"
markdown: kramdown
theme: just-the-docs
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
nav_external_links:
  - title: Discord
    url: https://discord.gg/6mFNszX8qM
  - title: GitHub
    url: https://github.com/bitmagnet-io/bitmagnet
  - title: OpenCollective
    url: https://opencollective.com/bitmagnet
favicon_ico: "/assets/images/favicon.png"
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-target-blank
