source 'https://rubygems.org'

gem "just-the-docs", "~> 0.6"
gem "jekyll", "~> 4.3"
gem "jekyll-redirect-from", "~> 0.16"
gem "kramdown", "~> 2.3"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.8"
