source 'https://rubygems.org'

gem "just-the-docs", "~> 0.10"
gem "jekyll", "~> 4.3"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-seo-tag"
gem "jekyll-target-blank", "~> 2.0"
gem "kramdown", "~> 2.4"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.8"
