// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package level

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
)

const (
	LevelDebug Level = "debug"
	LevelInfo  Level = "info"
	LevelWarn  Level = "warn"
	LevelError Level = "error"
)

var ErrInvalidLevel = fmt.Errorf("not a valid Level, try [%s]", strings.Join(_LevelNames, ", "))

var _LevelNames = []string{
	string(LevelDebug),
	string(LevelInfo),
	string(LevelWarn),
	string(LevelError),
}

// LevelNames returns a list of possible string values of Level.
func LevelNames() []string {
	tmp := make([]string, len(_LevelNames))
	copy(tmp, _LevelNames)
	return tmp
}

// LevelValues returns a list of the values for Level
func LevelValues() []Level {
	return []Level{
		LevelDebug,
		LevelInfo,
		LevelWarn,
		LevelError,
	}
}

// String implements the Stringer interface.
func (x Level) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Level) IsValid() bool {
	_, err := ParseLevel(string(x))
	return err == nil
}

var _LevelValue = map[string]Level{
	"debug": LevelDebug,
	"info":  LevelInfo,
	"warn":  LevelWarn,
	"error": LevelError,
}

// ParseLevel attempts to convert a string to a Level.
func ParseLevel(name string) (Level, error) {
	if x, ok := _LevelValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _LevelValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Level(""), fmt.Errorf("%s is %w", name, ErrInvalidLevel)
}

// MarshalText implements the text marshaller method.
func (x Level) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Level) UnmarshalText(text []byte) error {
	tmp, err := ParseLevel(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errLevelNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Level) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Level("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseLevel(v)
	case []byte:
		*x, err = ParseLevel(string(v))
	case Level:
		*x = v
	case *Level:
		if v == nil {
			return errLevelNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errLevelNilPtr
		}
		*x, err = ParseLevel(*v)
	default:
		return errors.New("invalid type for Level")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Level) Value() (driver.Value, error) {
	return x.String(), nil
}

type NullLevel struct {
	Level Level
	Valid bool
	Set   bool
}

func NewNullLevel(val interface{}) (x NullLevel) {
	err := x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	_ = err            // make any errcheck linters happy
	return
}

// Scan implements the Scanner interface.
func (x *NullLevel) Scan(value interface{}) (err error) {
	if value == nil {
		x.Level, x.Valid = Level(""), false
		return
	}

	err = x.Level.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullLevel) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.Level.String(), nil
}

// MarshalJSON correctly serializes a NullLevel to JSON.
func (n NullLevel) MarshalJSON() ([]byte, error) {
	const nullStr = "null"
	if n.Valid {
		return json.Marshal(n.Level)
	}
	return []byte(nullStr), nil
}

// UnmarshalJSON correctly deserializes a NullLevel from JSON.
func (n *NullLevel) UnmarshalJSON(b []byte) error {
	n.Set = true
	var x interface{}
	err := json.Unmarshal(b, &x)
	if err != nil {
		return err
	}
	err = n.Scan(x)
	return err
}

// MarshalGQL correctly serializes a NullLevel to GraphQL.
func (n NullLevel) MarshalGQL(w io.Writer) {
	bytes, err := json.Marshal(n)
	if err == nil {
		_, _ = w.Write(bytes)
	}
}

// UnmarshalGQL correctly deserializes a NullLevel from GraphQL.
func (n *NullLevel) UnmarshalGQL(v any) error {
	if v == nil {
		return nil
	}
	str, ok := v.(string)
	if !ok {
		return errors.New("value is not a string")
	}
	if str == "null" {
		return nil
	}
	return n.UnmarshalJSON([]byte("\"" + str + "\""))
}
