// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: api/api.proto

package api

import (
	"context"
	http "github.com/bitmagnet-io/bitmagnet/proto/common/http"
	model "github.com/bitmagnet-io/bitmagnet/proto/common/model"
	plugin "github.com/bitmagnet-io/bitmagnet/proto/common/plugin"
	search "github.com/bitmagnet-io/bitmagnet/proto/common/search"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type IndexPayload struct {
	state                protoimpl.MessageState
	sizeCache            protoimpl.SizeCache
	unknownFields        protoimpl.UnknownFields
	Content              []*model.Content        `json:"content,omitempty" protobuf:"bytes,1,rep,name=content,proto3"`
	TorrentContent       []*model.TorrentContent `json:"torrentContent,omitempty" protobuf:"bytes,2,rep,name=torrentContent,proto3"`
	DeleteTorrentContent []string                `json:"deleteTorrentContent,omitempty" protobuf:"bytes,3,rep,name=deleteTorrentContent,proto3"`
	DeleteInfoHashes     []string                `json:"deleteInfoHashes,omitempty" protobuf:"bytes,4,rep,name=deleteInfoHashes,proto3"`
}

func (x *IndexPayload) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *IndexPayload) GetContent() []*model.Content {
	if x != nil {
		return x.Content
	}

	var zero []*model.Content

	return zero
}

func (x *IndexPayload) GetTorrentContent() []*model.TorrentContent {
	if x != nil {
		return x.TorrentContent
	}

	var zero []*model.TorrentContent

	return zero
}

func (x *IndexPayload) GetDeleteTorrentContent() []string {
	if x != nil {
		return x.DeleteTorrentContent
	}

	var zero []string

	return zero
}

func (x *IndexPayload) GetDeleteInfoHashes() []string {
	if x != nil {
		return x.DeleteInfoHashes
	}

	var zero []string

	return zero
}

type HTTPHandlerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Pattern       string `json:"pattern,omitempty" protobuf:"bytes,1,opt,name=pattern,proto3"`
}

func (x *HTTPHandlerConfig) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *HTTPHandlerConfig) GetPattern() string {
	if x != nil {
		return x.Pattern
	}

	var zero string

	return zero
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Empty         string `json:"empty,omitempty" protobuf:"bytes,1,opt,name=empty,proto3"`
}

func (x *Empty) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Empty) GetEmpty() string {
	if x != nil {
		return x.Empty
	}

	var zero string

	return zero
}

type JSONPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Data          []byte `json:"data,omitempty" protobuf:"bytes,1,opt,name=data,proto3"`
}

func (x *JSONPayload) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *JSONPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}

	var zero []byte

	return zero
}

type LocalizeParams struct {
	state          protoimpl.MessageState
	sizeCache      protoimpl.SizeCache
	unknownFields  protoimpl.UnknownFields
	AcceptLanguage []string `json:"acceptLanguage,omitempty" protobuf:"bytes,1,rep,name=acceptLanguage,proto3"`
}

func (x *LocalizeParams) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *LocalizeParams) GetAcceptLanguage() []string {
	if x != nil {
		return x.AcceptLanguage
	}

	var zero []string

	return zero
}

type SendTorrentsParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Torrents      []*model.TorrentContent `json:"torrents,omitempty" protobuf:"bytes,1,rep,name=torrents,proto3"`
	Data          []byte                  `json:"data,omitempty" protobuf:"bytes,2,opt,name=data,proto3"`
}

func (x *SendTorrentsParams) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *SendTorrentsParams) GetTorrents() []*model.TorrentContent {
	if x != nil {
		return x.Torrents
	}

	var zero []*model.TorrentContent

	return zero
}

func (x *SendTorrentsParams) GetData() []byte {
	if x != nil {
		return x.Data
	}

	var zero []byte

	return zero
}

type Plugin interface {
	Identify(ctx context.Context, empty *Empty) (*plugin.Identity, error)
	Localize(ctx context.Context, localizeParams *LocalizeParams) (*plugin.LocalizedContent, error)
	Configure(ctx context.Context, jsonpayload *JSONPayload) (*plugin.Contract, error)
	Instantiate(ctx context.Context, empty *Empty) (*Empty, error)
}

type Indexer interface {
	Index(ctx context.Context, indexPayload *IndexPayload) (*Empty, error)
}

type HTTPHandler interface {
	Config(ctx context.Context, empty *Empty) (*HTTPHandlerConfig, error)
	HandleRequest(ctx context.Context, request *http.Request) (*http.Response, error)
}

type SearchAdapter interface {
	SearchTorrentContent(ctx context.Context, params *search.Params) (*search.TorrentContentResult, error)
	SearchTorrentFiles(ctx context.Context, params *search.Params) (*search.TorrentFilesResult, error)
}

type TorrentTarget interface {
	DataSchema(ctx context.Context, empty *Empty) (*JSONPayload, error)
	UISchema(ctx context.Context, localizeParams *LocalizeParams) (*JSONPayload, error)
	Send(ctx context.Context, sendTorrentsParams *SendTorrentsParams) (*JSONPayload, error)
}
