// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: api/api.proto

package api

import (
	"context"
	http "github.com/bitmagnet-io/bitmagnet/proto/common/http"
	model "github.com/bitmagnet-io/bitmagnet/proto/common/model"
	search "github.com/bitmagnet-io/bitmagnet/proto/common/search"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type IndexPayload struct {
	state                protoimpl.MessageState
	sizeCache            protoimpl.SizeCache
	unknownFields        protoimpl.UnknownFields
	Content              []*model.Content        `json:"content,omitempty" protobuf:"bytes,1,rep,name=content,proto3"`
	TorrentContent       []*model.TorrentContent `json:"torrentContent,omitempty" protobuf:"bytes,2,rep,name=torrentContent,proto3"`
	DeleteTorrentContent []string                `json:"deleteTorrentContent,omitempty" protobuf:"bytes,3,rep,name=deleteTorrentContent,proto3"`
	DeleteInfoHashes     []string                `json:"deleteInfoHashes,omitempty" protobuf:"bytes,4,rep,name=deleteInfoHashes,proto3"`
}

func (x *IndexPayload) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *IndexPayload) GetContent() []*model.Content {
	if x != nil {
		return x.Content
	}

	var zero []*model.Content

	return zero
}

func (x *IndexPayload) GetTorrentContent() []*model.TorrentContent {
	if x != nil {
		return x.TorrentContent
	}

	var zero []*model.TorrentContent

	return zero
}

func (x *IndexPayload) GetDeleteTorrentContent() []string {
	if x != nil {
		return x.DeleteTorrentContent
	}

	var zero []string

	return zero
}

func (x *IndexPayload) GetDeleteInfoHashes() []string {
	if x != nil {
		return x.DeleteInfoHashes
	}

	var zero []string

	return zero
}

type HTTPHandlerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Pattern       string `json:"pattern,omitempty" protobuf:"bytes,1,opt,name=pattern,proto3"`
}

func (x *HTTPHandlerConfig) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *HTTPHandlerConfig) GetPattern() string {
	if x != nil {
		return x.Pattern
	}

	var zero string

	return zero
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Empty         string `json:"empty,omitempty" protobuf:"bytes,1,opt,name=empty,proto3"`
}

func (x *Empty) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Empty) GetEmpty() string {
	if x != nil {
		return x.Empty
	}

	var zero string

	return zero
}

type Indexer interface {
	Index(ctx context.Context, indexPayload *IndexPayload) (*Empty, error)
}

type HTTPHandler interface {
	Config(ctx context.Context, empty *Empty) (*HTTPHandlerConfig, error)
	HandleRequest(ctx context.Context, request *http.Request) (*http.Response, error)
}

type SearchAdapter interface {
	SearchTorrentContent(ctx context.Context, params *search.Params) (*search.TorrentContentResult, error)
	SearchTorrentFiles(ctx context.Context, params *search.Params) (*search.TorrentFilesResult, error)
}
