//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: api/api.proto

package api

import (
	"context"
	wasm "github.com/bitmagnet-io/bitmagnet/internal/wasm"
	http "github.com/bitmagnet-io/bitmagnet/proto/common/http"
	search "github.com/bitmagnet-io/bitmagnet/proto/common/search"
)

const PluginPluginAPIVersion = 1

//go:wasmexport plugin_api_version
func _plugin_api_version() uint64 {
	return PluginPluginAPIVersion
}

var pluginService Plugin

func RegisterPlugin(p Plugin) {
	pluginService = p
}

//go:wasmexport plugin_identify
func _plugin_identify(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(Empty)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := pluginService.Identify(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport plugin_localize
func _plugin_localize(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(LocalizeParams)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := pluginService.Localize(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport plugin_configure
func _plugin_configure(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(JSONPayload)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := pluginService.Configure(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport plugin_instantiate
func _plugin_instantiate(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(Empty)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := pluginService.Instantiate(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

const IndexerPluginAPIVersion = 1

//go:wasmexport indexer_api_version
func _indexer_api_version() uint64 {
	return IndexerPluginAPIVersion
}

var indexerService Indexer

func RegisterIndexer(p Indexer) {
	indexerService = p
}

//go:wasmexport indexer_index
func _indexer_index(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(IndexPayload)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := indexerService.Index(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

const HTTPHandlerPluginAPIVersion = 1

//go:wasmexport http_handler_api_version
func _http_handler_api_version() uint64 {
	return HTTPHandlerPluginAPIVersion
}

var httphandlerService HTTPHandler

func RegisterHTTPHandler(p HTTPHandler) {
	httphandlerService = p
}

//go:wasmexport http_handler_config
func _http_handler_config(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(Empty)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := httphandlerService.Config(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport http_handler_handle_request
func _http_handler_handle_request(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(http.Request)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := httphandlerService.HandleRequest(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

const SearchAdapterPluginAPIVersion = 1

//go:wasmexport search_adapter_api_version
func _search_adapter_api_version() uint64 {
	return SearchAdapterPluginAPIVersion
}

var searchAdapterService SearchAdapter

func RegisterSearchAdapter(p SearchAdapter) {
	searchAdapterService = p
}

//go:wasmexport search_adapter_search_torrent_content
func _search_adapter_search_torrent_content(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(search.Params)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := searchAdapterService.SearchTorrentContent(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport search_adapter_search_torrent_files
func _search_adapter_search_torrent_files(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(search.Params)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := searchAdapterService.SearchTorrentFiles(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

const TorrentTargetPluginAPIVersion = 1

//go:wasmexport torrent_target_api_version
func _torrent_target_api_version() uint64 {
	return TorrentTargetPluginAPIVersion
}

var torrentTargetService TorrentTarget

func RegisterTorrentTarget(p TorrentTarget) {
	torrentTargetService = p
}

//go:wasmexport torrent_target_data_schema
func _torrent_target_data_schema(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(Empty)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := torrentTargetService.DataSchema(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport torrent_target_ui_schema
func _torrent_target_ui_schema(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(LocalizeParams)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := torrentTargetService.UISchema(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport torrent_target_send
func _torrent_target_send(ptr uint32, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(SendTorrentsParams)
	err := req.UnmarshalVT(b)
	if err != nil {
		panic(err)
	}
	resp, err := torrentTargetService.Send(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) | (1 << 31)
	}
	b, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
