//go:build !wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: api/api.proto

package api

import (
	"context"
	"errors"
	"fmt"
	http "github.com/bitmagnet-io/bitmagnet/proto/common/http"
	search "github.com/bitmagnet-io/bitmagnet/proto/common/search"
	api "github.com/tetratelabs/wazero/api"
)

const IndexerPluginAPIVersion = 1

type IndexerPlugin struct{}

func (p *IndexerPlugin) LoadModule(ctx context.Context, module api.Module) (Indexer, error) {
	apiVersion := module.ExportedFunction("indexer_api_version")
	if apiVersion == nil {
		return nil, errors.New("indexer_api_version is not exported")
	}
	results, err := apiVersion.Call(ctx)
	if err != nil {
		return nil, err
	} else if len(results) != 1 {
		return nil, errors.New("invalid indexer_api_version signature")
	}
	if results[0] != IndexerPluginAPIVersion {
		return nil, fmt.Errorf("API version mismatch, host: %d, plugin: %d", IndexerPluginAPIVersion, results[0])
	}
	index := module.ExportedFunction("indexer_index")
	if index == nil {
		return nil, errors.New("indexer_index is not exported")
	}
	malloc := module.ExportedFunction("malloc")
	if malloc == nil {
		return nil, errors.New("malloc is not exported")
	}
	free := module.ExportedFunction("free")
	if free == nil {
		return nil, errors.New("free is not exported")
	}
	return &indexerPlugin{
		module: module,
		malloc: malloc,
		free:   free,
		index:  index,
	}, nil
}

type indexerPlugin struct {
	module api.Module
	malloc api.Function
	free   api.Function
	index  api.Function
}

func (p *indexerPlugin) Index(ctx context.Context, request *IndexPayload) (*Empty, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.index.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(Empty)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}

const HTTPHandlerPluginAPIVersion = 1

type HTTPHandlerPlugin struct{}

func (p *HTTPHandlerPlugin) LoadModule(ctx context.Context, module api.Module) (HTTPHandler, error) {
	apiVersion := module.ExportedFunction("http_handler_api_version")
	if apiVersion == nil {
		return nil, errors.New("http_handler_api_version is not exported")
	}
	results, err := apiVersion.Call(ctx)
	if err != nil {
		return nil, err
	} else if len(results) != 1 {
		return nil, errors.New("invalid http_handler_api_version signature")
	}
	if results[0] != HTTPHandlerPluginAPIVersion {
		return nil, fmt.Errorf("API version mismatch, host: %d, plugin: %d", HTTPHandlerPluginAPIVersion, results[0])
	}
	config := module.ExportedFunction("http_handler_config")
	if config == nil {
		return nil, errors.New("http_handler_config is not exported")
	}
	handleRequest := module.ExportedFunction("http_handler_handle_request")
	if handleRequest == nil {
		return nil, errors.New("http_handler_handle_request is not exported")
	}
	malloc := module.ExportedFunction("malloc")
	if malloc == nil {
		return nil, errors.New("malloc is not exported")
	}
	free := module.ExportedFunction("free")
	if free == nil {
		return nil, errors.New("free is not exported")
	}
	return &httphandlerPlugin{
		module:        module,
		malloc:        malloc,
		free:          free,
		config:        config,
		handleRequest: handleRequest,
	}, nil
}

type httphandlerPlugin struct {
	module        api.Module
	malloc        api.Function
	free          api.Function
	config        api.Function
	handleRequest api.Function
}

func (p *httphandlerPlugin) Config(ctx context.Context, request *Empty) (*HTTPHandlerConfig, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.config.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(HTTPHandlerConfig)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}

func (p *httphandlerPlugin) HandleRequest(ctx context.Context, request *http.Request) (*http.Response, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.handleRequest.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(http.Response)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}

const SearchAdapterPluginAPIVersion = 1

type SearchAdapterPlugin struct{}

func (p *SearchAdapterPlugin) LoadModule(ctx context.Context, module api.Module) (SearchAdapter, error) {
	apiVersion := module.ExportedFunction("search_adapter_api_version")
	if apiVersion == nil {
		return nil, errors.New("search_adapter_api_version is not exported")
	}
	results, err := apiVersion.Call(ctx)
	if err != nil {
		return nil, err
	} else if len(results) != 1 {
		return nil, errors.New("invalid search_adapter_api_version signature")
	}
	if results[0] != SearchAdapterPluginAPIVersion {
		return nil, fmt.Errorf("API version mismatch, host: %d, plugin: %d", SearchAdapterPluginAPIVersion, results[0])
	}
	searchTorrentContent := module.ExportedFunction("search_adapter_search_torrent_content")
	if searchTorrentContent == nil {
		return nil, errors.New("search_adapter_search_torrent_content is not exported")
	}
	searchTorrentFiles := module.ExportedFunction("search_adapter_search_torrent_files")
	if searchTorrentFiles == nil {
		return nil, errors.New("search_adapter_search_torrent_files is not exported")
	}
	malloc := module.ExportedFunction("malloc")
	if malloc == nil {
		return nil, errors.New("malloc is not exported")
	}
	free := module.ExportedFunction("free")
	if free == nil {
		return nil, errors.New("free is not exported")
	}
	return &searchAdapterPlugin{
		module:               module,
		malloc:               malloc,
		free:                 free,
		searchTorrentContent: searchTorrentContent,
		searchTorrentFiles:   searchTorrentFiles,
	}, nil
}

type searchAdapterPlugin struct {
	module               api.Module
	malloc               api.Function
	free                 api.Function
	searchTorrentContent api.Function
	searchTorrentFiles   api.Function
}

func (p *searchAdapterPlugin) SearchTorrentContent(ctx context.Context, request *search.Params) (*search.TorrentContentResult, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.searchTorrentContent.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(search.TorrentContentResult)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}

func (p *searchAdapterPlugin) SearchTorrentFiles(ctx context.Context, request *search.Params) (*search.TorrentFilesResult, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.searchTorrentFiles.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(search.TorrentFilesResult)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}

const TorrentTargetPluginAPIVersion = 1

type TorrentTargetPlugin struct{}

func (p *TorrentTargetPlugin) LoadModule(ctx context.Context, module api.Module) (TorrentTarget, error) {
	apiVersion := module.ExportedFunction("torrent_target_api_version")
	if apiVersion == nil {
		return nil, errors.New("torrent_target_api_version is not exported")
	}
	results, err := apiVersion.Call(ctx)
	if err != nil {
		return nil, err
	} else if len(results) != 1 {
		return nil, errors.New("invalid torrent_target_api_version signature")
	}
	if results[0] != TorrentTargetPluginAPIVersion {
		return nil, fmt.Errorf("API version mismatch, host: %d, plugin: %d", TorrentTargetPluginAPIVersion, results[0])
	}
	dataSchema := module.ExportedFunction("torrent_target_data_schema")
	if dataSchema == nil {
		return nil, errors.New("torrent_target_data_schema is not exported")
	}
	uischema := module.ExportedFunction("torrent_target_ui_schema")
	if uischema == nil {
		return nil, errors.New("torrent_target_ui_schema is not exported")
	}
	send := module.ExportedFunction("torrent_target_send")
	if send == nil {
		return nil, errors.New("torrent_target_send is not exported")
	}
	malloc := module.ExportedFunction("malloc")
	if malloc == nil {
		return nil, errors.New("malloc is not exported")
	}
	free := module.ExportedFunction("free")
	if free == nil {
		return nil, errors.New("free is not exported")
	}
	return &torrentTargetPlugin{
		module:     module,
		malloc:     malloc,
		free:       free,
		dataSchema: dataSchema,
		uischema:   uischema,
		send:       send,
	}, nil
}

type torrentTargetPlugin struct {
	module     api.Module
	malloc     api.Function
	free       api.Function
	dataSchema api.Function
	uischema   api.Function
	send       api.Function
}

func (p *torrentTargetPlugin) DataSchema(ctx context.Context, request *Empty) (*JSONPayload, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.dataSchema.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(JSONPayload)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}

func (p *torrentTargetPlugin) UISchema(ctx context.Context, request *SendTorrentsUISchemaParams) (*JSONPayload, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.uischema.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(JSONPayload)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}

func (p *torrentTargetPlugin) Send(ctx context.Context, request *SendTorrentsParams) (*JSONPayload, error) {
	data, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	var ptr uint64
	dataSize := len(data)
	if dataSize != 0 {
		results, err := p.malloc.Call(ctx, uint64(dataSize))
		if err != nil {
			return nil, err
		}
		ptr = uint64(results[0])
		defer p.free.Call(ctx, ptr)
		if !p.module.Memory().Write(uint32(ptr), data) {
			return nil, fmt.Errorf("out of range memory size")
		}
	}
	ptrSize, err := p.send.Call(ctx, ptr, uint64(dataSize))
	if err != nil {
		return nil, err
	}
	resPtr := uint32(ptrSize[0] >> 32)
	resSize := uint32(ptrSize[0])
	var isErrResponse bool
	if resSize&(1<<31) > 0 {
		isErrResponse = true
		resSize &^= (1 << 31)
	}
	if resPtr != 0 {
		defer p.free.Call(ctx, uint64(resPtr))
	}
	bytes, ok := p.module.Memory().Read(resPtr, resSize)
	if !ok {
		return nil, fmt.Errorf("out of range memory size")
	}
	if isErrResponse {
		return nil, errors.New(string(bytes))
	}
	response := new(JSONPayload)
	if err = response.UnmarshalVT(bytes); err != nil {
		return nil, err
	}
	return response, nil
}
