// Code generated by mockery v2.52.1. DO NOT EDIT.

package rbac_mocks

import (
	context "context"

	rbac "github.com/bitmagnet-io/bitmagnet/internal/auth/rbac"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// DeleteRole provides a mock function with given fields: ctx, role
func (_m *Repository) DeleteRole(ctx context.Context, role rbac.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rbac.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type Repository_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role rbac.Role
func (_e *Repository_Expecter) DeleteRole(ctx interface{}, role interface{}) *Repository_DeleteRole_Call {
	return &Repository_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, role)}
}

func (_c *Repository_DeleteRole_Call) Run(run func(ctx context.Context, role rbac.Role)) *Repository_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rbac.Role))
	})
	return _c
}

func (_c *Repository_DeleteRole_Call) Return(_a0 error) *Repository_DeleteRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteRole_Call) RunAndReturn(run func(context.Context, rbac.Role) error) *Repository_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRoles provides a mock function with given fields: ctx
func (_m *Repository) GetAllRoles(ctx context.Context) ([]rbac.RoleInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRoles")
	}

	var r0 []rbac.RoleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]rbac.RoleInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []rbac.RoleInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rbac.RoleInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAllRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRoles'
type Repository_GetAllRoles_Call struct {
	*mock.Call
}

// GetAllRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) GetAllRoles(ctx interface{}) *Repository_GetAllRoles_Call {
	return &Repository_GetAllRoles_Call{Call: _e.mock.On("GetAllRoles", ctx)}
}

func (_c *Repository_GetAllRoles_Call) Run(run func(ctx context.Context)) *Repository_GetAllRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_GetAllRoles_Call) Return(_a0 []rbac.RoleInfo, _a1 error) *Repository_GetAllRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAllRoles_Call) RunAndReturn(run func(context.Context) ([]rbac.RoleInfo, error)) *Repository_GetAllRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function with given fields: ctx
func (_m *Repository) GetPermissions(ctx context.Context) ([]rbac.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []rbac.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]rbac.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []rbac.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rbac.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type Repository_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) GetPermissions(ctx interface{}) *Repository_GetPermissions_Call {
	return &Repository_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx)}
}

func (_c *Repository_GetPermissions_Call) Run(run func(ctx context.Context)) *Repository_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_GetPermissions_Call) Return(_a0 []rbac.Permission, _a1 error) *Repository_GetPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetPermissions_Call) RunAndReturn(run func(context.Context) ([]rbac.Permission, error)) *Repository_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function with given fields: ctx, roles
func (_m *Repository) GetRole(ctx context.Context, roles rbac.Role) (rbac.RoleInfo, error) {
	ret := _m.Called(ctx, roles)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 rbac.RoleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rbac.Role) (rbac.RoleInfo, error)); ok {
		return rf(ctx, roles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rbac.Role) rbac.RoleInfo); ok {
		r0 = rf(ctx, roles)
	} else {
		r0 = ret.Get(0).(rbac.RoleInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, rbac.Role) error); ok {
		r1 = rf(ctx, roles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type Repository_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roles rbac.Role
func (_e *Repository_Expecter) GetRole(ctx interface{}, roles interface{}) *Repository_GetRole_Call {
	return &Repository_GetRole_Call{Call: _e.mock.On("GetRole", ctx, roles)}
}

func (_c *Repository_GetRole_Call) Run(run func(ctx context.Context, roles rbac.Role)) *Repository_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rbac.Role))
	})
	return _c
}

func (_c *Repository_GetRole_Call) Return(_a0 rbac.RoleInfo, _a1 error) *Repository_GetRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetRole_Call) RunAndReturn(run func(context.Context, rbac.Role) (rbac.RoleInfo, error)) *Repository_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function with given fields: ctx, roles
func (_m *Repository) GetRoles(ctx context.Context, roles []rbac.Role) ([]rbac.RoleInfo, error) {
	ret := _m.Called(ctx, roles)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []rbac.RoleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []rbac.Role) ([]rbac.RoleInfo, error)); ok {
		return rf(ctx, roles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []rbac.Role) []rbac.RoleInfo); ok {
		r0 = rf(ctx, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rbac.RoleInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []rbac.Role) error); ok {
		r1 = rf(ctx, roles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type Repository_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - roles []rbac.Role
func (_e *Repository_Expecter) GetRoles(ctx interface{}, roles interface{}) *Repository_GetRoles_Call {
	return &Repository_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx, roles)}
}

func (_c *Repository_GetRoles_Call) Run(run func(ctx context.Context, roles []rbac.Role)) *Repository_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]rbac.Role))
	})
	return _c
}

func (_c *Repository_GetRoles_Call) Return(_a0 []rbac.RoleInfo, _a1 error) *Repository_GetRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetRoles_Call) RunAndReturn(run func(context.Context, []rbac.Role) ([]rbac.RoleInfo, error)) *Repository_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// PutRole provides a mock function with given fields: ctx, role, objectActions
func (_m *Repository) PutRole(ctx context.Context, role rbac.Role, objectActions []rbac.ObjectAction) (rbac.RoleInfo, error) {
	ret := _m.Called(ctx, role, objectActions)

	if len(ret) == 0 {
		panic("no return value specified for PutRole")
	}

	var r0 rbac.RoleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rbac.Role, []rbac.ObjectAction) (rbac.RoleInfo, error)); ok {
		return rf(ctx, role, objectActions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rbac.Role, []rbac.ObjectAction) rbac.RoleInfo); ok {
		r0 = rf(ctx, role, objectActions)
	} else {
		r0 = ret.Get(0).(rbac.RoleInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, rbac.Role, []rbac.ObjectAction) error); ok {
		r1 = rf(ctx, role, objectActions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_PutRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRole'
type Repository_PutRole_Call struct {
	*mock.Call
}

// PutRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role rbac.Role
//   - objectActions []rbac.ObjectAction
func (_e *Repository_Expecter) PutRole(ctx interface{}, role interface{}, objectActions interface{}) *Repository_PutRole_Call {
	return &Repository_PutRole_Call{Call: _e.mock.On("PutRole", ctx, role, objectActions)}
}

func (_c *Repository_PutRole_Call) Run(run func(ctx context.Context, role rbac.Role, objectActions []rbac.ObjectAction)) *Repository_PutRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rbac.Role), args[2].([]rbac.ObjectAction))
	})
	return _c
}

func (_c *Repository_PutRole_Call) Return(_a0 rbac.RoleInfo, _a1 error) *Repository_PutRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_PutRole_Call) RunAndReturn(run func(context.Context, rbac.Role, []rbac.ObjectAction) (rbac.RoleInfo, error)) *Repository_PutRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
