// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: common/plugin/plugin.proto

package plugin

import (
	http "github.com/bitmagnet-io/bitmagnet/proto/common/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	/*
	   Default name of the plugin; must be lower_snake_case.
	*/
	Name         string         `json:"name,omitempty" protobuf:"bytes,1,opt,name=name,proto3"`
	Version      string         `json:"version,omitempty" protobuf:"bytes,2,opt,name=version,proto3"`
	ConfigParams []*ConfigParam `json:"configParams,omitempty" protobuf:"bytes,3,rep,name=configParams,proto3"`
}

func (x *Identity) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

/*
Default name of the plugin; must be lower_snake_case.
*/
func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

func (x *Identity) GetVersion() string {
	if x != nil {
		return x.Version
	}

	var zero string

	return zero
}

func (x *Identity) GetConfigParams() []*ConfigParam {
	if x != nil {
		return x.ConfigParams
	}

	var zero []*ConfigParam

	return zero
}

type ConfigParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	/*
	   Name of the configuration parameter; must be lower_snake_case.
	*/
	Name string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name,proto3"`
	/*
	   JSON schema for the configuration parameter.
	*/
	Schema []byte `json:"schema,omitempty" protobuf:"bytes,2,opt,name=schema,proto3"`
}

func (x *ConfigParam) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

/*
Name of the configuration parameter; must be lower_snake_case.
*/
func (x *ConfigParam) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

/*
JSON schema for the configuration parameter.
*/
func (x *ConfigParam) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}

	var zero []byte

	return zero
}

type LocalizedContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	/*
	   Localized description of the plugin.
	*/
	Description string `json:"description,omitempty" protobuf:"bytes,1,opt,name=description,proto3"`
	/*
	   Localized descriptions for configuration parameters; names must match those in ConfigParam.
	*/
	ConfigParams []*ConfigParamLocalizedContent `json:"configParams,omitempty" protobuf:"bytes,2,rep,name=configParams,proto3"`
}

func (x *LocalizedContent) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

/*
Localized description of the plugin.
*/
func (x *LocalizedContent) GetDescription() string {
	if x != nil {
		return x.Description
	}

	var zero string

	return zero
}

/*
Localized descriptions for configuration parameters; names must match those in ConfigParam.
*/
func (x *LocalizedContent) GetConfigParams() []*ConfigParamLocalizedContent {
	if x != nil {
		return x.ConfigParams
	}

	var zero []*ConfigParamLocalizedContent

	return zero
}

type ConfigParamLocalizedContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	/*
	   Name of the configuration parameter; must be lower_snake_case.
	*/
	Name string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name,proto3"`
	/*
	   Localized description for the configuration parameter.
	*/
	Description string `json:"description,omitempty" protobuf:"bytes,2,opt,name=description,proto3"`
}

func (x *ConfigParamLocalizedContent) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

/*
Name of the configuration parameter; must be lower_snake_case.
*/
func (x *ConfigParamLocalizedContent) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

/*
Localized description for the configuration parameter.
*/
func (x *ConfigParamLocalizedContent) GetDescription() string {
	if x != nil {
		return x.Description
	}

	var zero string

	return zero
}

type Contract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Capabilities  *Capabilities `json:"capabilities,omitempty" protobuf:"bytes,1,opt,name=capabilities,proto3"`
	Permissions   *Permissions  `json:"permissions,omitempty" protobuf:"bytes,2,opt,name=permissions,proto3"`
}

func (x *Contract) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Contract) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}

	var zero *Capabilities

	return zero
}

func (x *Contract) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}

	var zero *Permissions

	return zero
}

type Capabilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Indexer       *CapabilityIndexer       `json:"indexer,omitempty" protobuf:"bytes,1,opt,name=indexer,proto3"`
	HttpHandler   *CapabilityHTTPHandler   `json:"httpHandler,omitempty" protobuf:"bytes,2,opt,name=httpHandler,proto3"`
	TorrentTarget *CapabilityTorrentTarget `json:"torrentTarget,omitempty" protobuf:"bytes,3,opt,name=torrentTarget,proto3"`
	SearchAdapter *CapabilitySearchAdapter `json:"searchAdapter,omitempty" protobuf:"bytes,4,opt,name=searchAdapter,proto3"`
}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Capabilities) GetIndexer() *CapabilityIndexer {
	if x != nil {
		return x.Indexer
	}

	var zero *CapabilityIndexer

	return zero
}

func (x *Capabilities) GetHttpHandler() *CapabilityHTTPHandler {
	if x != nil {
		return x.HttpHandler
	}

	var zero *CapabilityHTTPHandler

	return zero
}

func (x *Capabilities) GetTorrentTarget() *CapabilityTorrentTarget {
	if x != nil {
		return x.TorrentTarget
	}

	var zero *CapabilityTorrentTarget

	return zero
}

func (x *Capabilities) GetSearchAdapter() *CapabilitySearchAdapter {
	if x != nil {
		return x.SearchAdapter
	}

	var zero *CapabilitySearchAdapter

	return zero
}

type CapabilityIndexer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Name          string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name,proto3"`
}

func (x *CapabilityIndexer) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *CapabilityIndexer) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

type CapabilityHTTPHandler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Name          string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name,proto3"`
}

func (x *CapabilityHTTPHandler) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *CapabilityHTTPHandler) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

type CapabilitySearchAdapter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Name          string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name,proto3"`
}

func (x *CapabilitySearchAdapter) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *CapabilitySearchAdapter) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

type CapabilityTorrentTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Name          string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name,proto3"`
}

func (x *CapabilityTorrentTarget) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *CapabilityTorrentTarget) GetName() string {
	if x != nil {
		return x.Name
	}

	var zero string

	return zero
}

type Permissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Http          *PermissionHTTP `json:"http,omitempty" protobuf:"bytes,1,opt,name=http,proto3"`
}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *Permissions) GetHttp() *PermissionHTTP {
	if x != nil {
		return x.Http
	}

	var zero *PermissionHTTP

	return zero
}

type PermissionHTTP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Egress        []*http.Egress `json:"egress,omitempty" protobuf:"bytes,1,rep,name=egress,proto3"`
}

func (x *PermissionHTTP) ProtoReflect() protoreflect.Message {
	panic("not implemented")
}

func (x *PermissionHTTP) GetEgress() []*http.Egress {
	if x != nil {
		return x.Egress
	}

	var zero []*http.Egress

	return zero
}
