parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  project: "./tsconfig.json"
  sourceType: "module"
plugins:
  - "@typescript-eslint/eslint-plugin"
  - import
  - sonarjs
extends:
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:import/errors"
  - "plugin:import/typescript"
  - "plugin:sonarjs/recommended"
  - "plugin:prettier/recommended"
settings:
  import/resolver:
    typescript: true
    node: true
root: true
env:
  node: true
  jest: true
rules:
  "@typescript-eslint/return-await": error
  "import/order": error
  "no-console": error
  "prettier/prettier": warn
ignorePatterns:
  - "src/app/graphql/generated/**/*.*"
  - "**/*.html"
