// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package search

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

const (
	FacetReleaseYear     Facet = "release_year"
	FacetContentGenre    Facet = "content_genre"
	FacetLanguage        Facet = "language"
	FacetContentType     Facet = "content_type"
	FacetVideo3D         Facet = "video_3d"
	FacetVideoCodec      Facet = "video_codec"
	FacetVideoModifier   Facet = "video_modifier"
	FacetVideoResolution Facet = "video_resolution"
	FacetVideoSource     Facet = "video_source"
	FacetFileType        Facet = "file_type"
	FacetTorrentSource   Facet = "torrent_source"
	FacetTag             Facet = "tag"
)

var ErrInvalidFacet = fmt.Errorf("not a valid Facet, try [%s]", strings.Join(_FacetNames, ", "))

var _FacetNames = []string{
	string(FacetReleaseYear),
	string(FacetContentGenre),
	string(FacetLanguage),
	string(FacetContentType),
	string(FacetVideo3D),
	string(FacetVideoCodec),
	string(FacetVideoModifier),
	string(FacetVideoResolution),
	string(FacetVideoSource),
	string(FacetFileType),
	string(FacetTorrentSource),
	string(FacetTag),
}

// FacetNames returns a list of possible string values of Facet.
func FacetNames() []string {
	tmp := make([]string, len(_FacetNames))
	copy(tmp, _FacetNames)
	return tmp
}

// FacetValues returns a list of the values for Facet
func FacetValues() []Facet {
	return []Facet{
		FacetReleaseYear,
		FacetContentGenre,
		FacetLanguage,
		FacetContentType,
		FacetVideo3D,
		FacetVideoCodec,
		FacetVideoModifier,
		FacetVideoResolution,
		FacetVideoSource,
		FacetFileType,
		FacetTorrentSource,
		FacetTag,
	}
}

// String implements the Stringer interface.
func (x Facet) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Facet) IsValid() bool {
	_, err := ParseFacet(string(x))
	return err == nil
}

var _FacetValue = map[string]Facet{
	"release_year":     FacetReleaseYear,
	"content_genre":    FacetContentGenre,
	"language":         FacetLanguage,
	"content_type":     FacetContentType,
	"video_3d":         FacetVideo3D,
	"video_codec":      FacetVideoCodec,
	"video_modifier":   FacetVideoModifier,
	"video_resolution": FacetVideoResolution,
	"video_source":     FacetVideoSource,
	"file_type":        FacetFileType,
	"torrent_source":   FacetTorrentSource,
	"tag":              FacetTag,
}

// ParseFacet attempts to convert a string to a Facet.
func ParseFacet(name string) (Facet, error) {
	if x, ok := _FacetValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _FacetValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Facet(""), fmt.Errorf("%s is %w", name, ErrInvalidFacet)
}

// MarshalText implements the text marshaller method.
func (x Facet) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Facet) UnmarshalText(text []byte) error {
	tmp, err := ParseFacet(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errFacetNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Facet) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Facet("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseFacet(v)
	case []byte:
		*x, err = ParseFacet(string(v))
	case Facet:
		*x = v
	case *Facet:
		if v == nil {
			return errFacetNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errFacetNilPtr
		}
		*x, err = ParseFacet(*v)
	default:
		return errors.New("invalid type for Facet")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Facet) Value() (driver.Value, error) {
	return x.String(), nil
}

type NullFacet struct {
	Facet Facet
	Valid bool
	Set   bool
}

func NewNullFacet(val interface{}) (x NullFacet) {
	err := x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	_ = err            // make any errcheck linters happy
	return
}

// Scan implements the Scanner interface.
func (x *NullFacet) Scan(value interface{}) (err error) {
	if value == nil {
		x.Facet, x.Valid = Facet(""), false
		return
	}

	err = x.Facet.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullFacet) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.Facet.String(), nil
}

// MarshalJSON correctly serializes a NullFacet to JSON.
func (n NullFacet) MarshalJSON() ([]byte, error) {
	const nullStr = "null"
	if n.Valid {
		return json.Marshal(n.Facet)
	}
	return []byte(nullStr), nil
}

// UnmarshalJSON correctly deserializes a NullFacet from JSON.
func (n *NullFacet) UnmarshalJSON(b []byte) error {
	n.Set = true
	var x interface{}
	err := json.Unmarshal(b, &x)
	if err != nil {
		return err
	}
	err = n.Scan(x)
	return err
}
