// Code generated by mockery v2.52.1. DO NOT EDIT.

package health_mocks

import (
	context "context"

	health "github.com/bitmagnet-io/bitmagnet/internal/health"
	mock "github.com/stretchr/testify/mock"

	runner "github.com/bitmagnet-io/bitmagnet/internal/workers/runner"

	time "time"
)

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

type Checker_Expecter struct {
	mock *mock.Mock
}

func (_m *Checker) EXPECT() *Checker_Expecter {
	return &Checker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx
func (_m *Checker) Check(ctx context.Context) health.CheckerResult {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 health.CheckerResult
	if rf, ok := ret.Get(0).(func(context.Context) health.CheckerResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(health.CheckerResult)
	}

	return r0
}

// Checker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type Checker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Checker_Expecter) Check(ctx interface{}) *Checker_Check_Call {
	return &Checker_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *Checker_Check_Call) Run(run func(ctx context.Context)) *Checker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Checker_Check_Call) Return(_a0 health.CheckerResult) *Checker_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Checker_Check_Call) RunAndReturn(run func(context.Context) health.CheckerResult) *Checker_Check_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunningPeriodicCheckCount provides a mock function with no fields
func (_m *Checker) GetRunningPeriodicCheckCount() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRunningPeriodicCheckCount")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Checker_GetRunningPeriodicCheckCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunningPeriodicCheckCount'
type Checker_GetRunningPeriodicCheckCount_Call struct {
	*mock.Call
}

// GetRunningPeriodicCheckCount is a helper method to define mock.On call
func (_e *Checker_Expecter) GetRunningPeriodicCheckCount() *Checker_GetRunningPeriodicCheckCount_Call {
	return &Checker_GetRunningPeriodicCheckCount_Call{Call: _e.mock.On("GetRunningPeriodicCheckCount")}
}

func (_c *Checker_GetRunningPeriodicCheckCount_Call) Run(run func()) *Checker_GetRunningPeriodicCheckCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Checker_GetRunningPeriodicCheckCount_Call) Return(_a0 int) *Checker_GetRunningPeriodicCheckCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Checker_GetRunningPeriodicCheckCount_Call) RunAndReturn(run func() int) *Checker_GetRunningPeriodicCheckCount_Call {
	_c.Call.Return(run)
	return _c
}

// IsStarted provides a mock function with no fields
func (_m *Checker) IsStarted() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStarted")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Checker_IsStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStarted'
type Checker_IsStarted_Call struct {
	*mock.Call
}

// IsStarted is a helper method to define mock.On call
func (_e *Checker_Expecter) IsStarted() *Checker_IsStarted_Call {
	return &Checker_IsStarted_Call{Call: _e.mock.On("IsStarted")}
}

func (_c *Checker_IsStarted_Call) Run(run func()) *Checker_IsStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Checker_IsStarted_Call) Return(_a0 bool) *Checker_IsStarted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Checker_IsStarted_Call) RunAndReturn(run func() bool) *Checker_IsStarted_Call {
	_c.Call.Return(run)
	return _c
}

// Runner provides a mock function with given fields: ctx, cancel
func (_m *Checker) Runner(ctx context.Context, cancel context.CancelCauseFunc) (runner.Shutdowner, error) {
	ret := _m.Called(ctx, cancel)

	if len(ret) == 0 {
		panic("no return value specified for Runner")
	}

	var r0 runner.Shutdowner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, context.CancelCauseFunc) (runner.Shutdowner, error)); ok {
		return rf(ctx, cancel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, context.CancelCauseFunc) runner.Shutdowner); ok {
		r0 = rf(ctx, cancel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runner.Shutdowner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, context.CancelCauseFunc) error); ok {
		r1 = rf(ctx, cancel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Checker_Runner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Runner'
type Checker_Runner_Call struct {
	*mock.Call
}

// Runner is a helper method to define mock.On call
//   - ctx context.Context
//   - cancel context.CancelCauseFunc
func (_e *Checker_Expecter) Runner(ctx interface{}, cancel interface{}) *Checker_Runner_Call {
	return &Checker_Runner_Call{Call: _e.mock.On("Runner", ctx, cancel)}
}

func (_c *Checker_Runner_Call) Run(run func(ctx context.Context, cancel context.CancelCauseFunc)) *Checker_Runner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(context.CancelCauseFunc))
	})
	return _c
}

func (_c *Checker_Runner_Call) Return(_a0 runner.Shutdowner, _a1 error) *Checker_Runner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Checker_Runner_Call) RunAndReturn(run func(context.Context, context.CancelCauseFunc) (runner.Shutdowner, error)) *Checker_Runner_Call {
	_c.Call.Return(run)
	return _c
}

// StartedAt provides a mock function with no fields
func (_m *Checker) StartedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// Checker_StartedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartedAt'
type Checker_StartedAt_Call struct {
	*mock.Call
}

// StartedAt is a helper method to define mock.On call
func (_e *Checker_Expecter) StartedAt() *Checker_StartedAt_Call {
	return &Checker_StartedAt_Call{Call: _e.mock.On("StartedAt")}
}

func (_c *Checker_StartedAt_Call) Run(run func()) *Checker_StartedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Checker_StartedAt_Call) Return(_a0 time.Time) *Checker_StartedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Checker_StartedAt_Call) RunAndReturn(run func() time.Time) *Checker_StartedAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewChecker creates a new instance of Checker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Checker {
	mock := &Checker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
