// Code generated by mockery v2.52.1. DO NOT EDIT.

package health_mocks

import (
	http "net/http"

	health "github.com/bitmagnet-io/bitmagnet/internal/health"

	mock "github.com/stretchr/testify/mock"
)

// ResultWriter is an autogenerated mock type for the ResultWriter type
type ResultWriter struct {
	mock.Mock
}

type ResultWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *ResultWriter) EXPECT() *ResultWriter_Expecter {
	return &ResultWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: result, statusCode, w, r
func (_m *ResultWriter) Write(result *health.CheckerResult, statusCode int, w http.ResponseWriter, r *http.Request) error {
	ret := _m.Called(result, statusCode, w, r)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*health.CheckerResult, int, http.ResponseWriter, *http.Request) error); ok {
		r0 = rf(result, statusCode, w, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResultWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type ResultWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - result *health.CheckerResult
//   - statusCode int
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ResultWriter_Expecter) Write(result interface{}, statusCode interface{}, w interface{}, r interface{}) *ResultWriter_Write_Call {
	return &ResultWriter_Write_Call{Call: _e.mock.On("Write", result, statusCode, w, r)}
}

func (_c *ResultWriter_Write_Call) Run(run func(result *health.CheckerResult, statusCode int, w http.ResponseWriter, r *http.Request)) *ResultWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*health.CheckerResult), args[1].(int), args[2].(http.ResponseWriter), args[3].(*http.Request))
	})
	return _c
}

func (_c *ResultWriter_Write_Call) Return(_a0 error) *ResultWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResultWriter_Write_Call) RunAndReturn(run func(*health.CheckerResult, int, http.ResponseWriter, *http.Request) error) *ResultWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewResultWriter creates a new instance of ResultWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResultWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResultWriter {
	mock := &ResultWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
