package user

import "errors"

var (
	Err                            = errors.New("user")
	ErrInitialInvitation           = errors.New("initial invitation failed")
	ErrInvite                      = errors.New("invite failed")
	ErrRegister                    = errors.New("register failed")
	ErrLogin                       = errors.New("login failed")
	ErrUsernameInvalid             = errors.New("invalid username")
	ErrDisabled                    = errors.New("account is disabled")
	ErrEmailInvalid                = errors.New("invalid email")
	ErrEmailMissing                = errors.New("email is required")
	ErrAlreadyExists               = errors.New("user already exists")
	ErrCredentialsInvalid          = errors.New("invalid username or password")
	ErrInvitationCodeMissing       = errors.New("invitation code is required")
	ErrInvitationNotFound          = errors.New("invitation not found")
	ErrInvitationExpired           = errors.New("invitation expired")
	ErrInvitationClaimed           = errors.New("invitation already claimed")
	ErrNotFound                    = errors.New("user not found")
	ErrHasNoPassword               = errors.New("user has no password")
	ErrIncorrectPassword           = errors.New("password is incorrect")
	ErrAssignRole                  = errors.New("failed to assign role")
	ErrRoleNotFound                = errors.New("role not found")
	ErrUserRoleNotFound            = errors.New("user role not found")
	ErrGenerateToken               = errors.New("generate token failed")
	ErrGet                         = errors.New("get user failed")
	ErrPasswordInsufficientEntropy = errors.New("password has insufficient entropy")
	ErrUpdatePassword              = errors.New("update password failed")
	ErrTransaction                 = errors.New("database transaction failed")
	ErrList                        = errors.New("list users failed")
	ErrListInvitations             = errors.New("list invitations failed")
	ErrDelete                      = errors.New("delete user failed")
	ErrDeleteInvitation            = errors.New("delete invitation failed")
	ErrSetEnabled                  = errors.New("set enabled failed")
	ErrLoginRequestLimiter         = errors.New("too many login requests")
)
