//go:build !wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// protoc version: v5.29.4
// source: host/http_client/http_client.proto

package http_client

import (
	"context"
	wasm "github.com/bitmagnet-io/bitmagnet/internal/wasm"
	http "github.com/bitmagnet-io/bitmagnet/proto/common/http"
	wazero "github.com/tetratelabs/wazero"
	api "github.com/tetratelabs/wazero/api"
)

const (
	i32 = api.ValueTypeI32
	i64 = api.ValueTypeI64
)

type _service struct {
	Service
}

func Instantiate(ctx context.Context, r wazero.Runtime, hostFunctions Service) error {
	envBuilder := r.NewHostModuleBuilder("http_client")
	h := _service{hostFunctions}

	envBuilder.NewFunctionBuilder().WithGoModuleFunction(
		api.GoModuleFunc(h._Request),
		[]api.ValueType{i32, i32},
		[]api.ValueType{i64},
	).
		WithParameterNames("offset", "size").
		Export("request")

	_, err := envBuilder.Instantiate(ctx)
	return err
}

func (h _service) _Request(ctx context.Context, m api.Module, stack []uint64) {
	offset, size := uint32(stack[0]), uint32(stack[1])
	buf, err := wasm.ReadMemory(m.Memory(), offset, size)
	if err != nil {
		panic(err)
	}
	request := new(http.Request)
	err = request.UnmarshalVT(buf)
	if err != nil {
		panic(err)
	}
	resp, err := h.Request(ctx, request)
	if err != nil {
		panic(err)
	}
	buf, err = resp.MarshalVT()
	if err != nil {
		panic(err)
	}
	ptr, err := wasm.WriteMemory(ctx, m, buf)
	if err != nil {
		panic(err)
	}
	ptrLen := (ptr<<uint64(32) | uint64(len(buf)))
	stack[0] = ptrLen
}
